// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: ai_service.proto

package ai

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_OPENAI      Provider = 1
	Provider_PROVIDER_ANTHROPIC   Provider = 2
	Provider_PROVIDER_OLLAMA      Provider = 3
	Provider_PROVIDER_HUGGINGFACE Provider = 4
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_OPENAI",
		2: "PROVIDER_ANTHROPIC",
		3: "PROVIDER_OLLAMA",
		4: "PROVIDER_HUGGINGFACE",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_OPENAI":      1,
		"PROVIDER_ANTHROPIC":   2,
		"PROVIDER_OLLAMA":      3,
		"PROVIDER_HUGGINGFACE": 4,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[0].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[0]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

type HealthStatus int32

const (
	HealthStatus_HEALTH_UNKNOWN   HealthStatus = 0
	HealthStatus_HEALTH_HEALTHY   HealthStatus = 1
	HealthStatus_HEALTH_UNHEALTHY HealthStatus = 2
	HealthStatus_HEALTH_ERROR     HealthStatus = 3
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_UNKNOWN",
		1: "HEALTH_HEALTHY",
		2: "HEALTH_UNHEALTHY",
		3: "HEALTH_ERROR",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_UNKNOWN":   0,
		"HEALTH_HEALTHY":   1,
		"HEALTH_UNHEALTHY": 2,
		"HEALTH_ERROR":     3,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[1].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[1]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

type ErrorType int32

const (
	ErrorType_ERROR_UNKNOWN         ErrorType = 0
	ErrorType_ERROR_INVALID_REQUEST ErrorType = 1
	ErrorType_ERROR_PROVIDER_ERROR  ErrorType = 2
	ErrorType_ERROR_CONFIG_ERROR    ErrorType = 3
	ErrorType_ERROR_RATE_LIMIT      ErrorType = 4
	ErrorType_ERROR_TIMEOUT         ErrorType = 5
	ErrorType_ERROR_INTERNAL        ErrorType = 6
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "ERROR_UNKNOWN",
		1: "ERROR_INVALID_REQUEST",
		2: "ERROR_PROVIDER_ERROR",
		3: "ERROR_CONFIG_ERROR",
		4: "ERROR_RATE_LIMIT",
		5: "ERROR_TIMEOUT",
		6: "ERROR_INTERNAL",
	}
	ErrorType_value = map[string]int32{
		"ERROR_UNKNOWN":         0,
		"ERROR_INVALID_REQUEST": 1,
		"ERROR_PROVIDER_ERROR":  2,
		"ERROR_CONFIG_ERROR":    3,
		"ERROR_RATE_LIMIT":      4,
		"ERROR_TIMEOUT":         5,
		"ERROR_INTERNAL":        6,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_service_proto_enumTypes[2].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_ai_service_proto_enumTypes[2]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

// Core message types
type SQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`   // For fixing existing queries
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`   // Error message to fix
	Schema        string                 `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"` // Database schema context
	Provider      Provider               `protobuf:"varint,5,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,7,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float64                `protobuf:"fixed64,8,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Context       map[string]string      `protobuf:"bytes,9,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLRequest) Reset() {
	*x = SQLRequest{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLRequest) ProtoMessage() {}

func (x *SQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLRequest.ProtoReflect.Descriptor instead.
func (*SQLRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *SQLRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SQLRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SQLRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SQLRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *SQLRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *SQLRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SQLRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SQLRequest) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SQLRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type SQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Explanation   string                 `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Provider      Provider               `protobuf:"varint,6,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,8,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	TimeTaken     *durationpb.Duration   `protobuf:"bytes,9,opt,name=time_taken,json=timeTaken,proto3" json:"time_taken,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLResponse) Reset() {
	*x = SQLResponse{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLResponse) ProtoMessage() {}

func (x *SQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLResponse.ProtoReflect.Descriptor instead.
func (*SQLResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *SQLResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SQLResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SQLResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SQLResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SQLResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *SQLResponse) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *SQLResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *SQLResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *SQLResponse) GetTimeTaken() *durationpb.Duration {
	if x != nil {
		return x.TimeTaken
	}
	return nil
}

func (x *SQLResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Provider      Provider               `protobuf:"varint,3,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Capabilities  []string               `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ModelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelInfo) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ModelInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ModelInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProviderHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Status        HealthStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=ai.HealthStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LastChecked   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_checked,json=lastChecked,proto3" json:"last_checked,omitempty"`
	ResponseTime  *durationpb.Duration   `protobuf:"bytes,5,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealth) Reset() {
	*x = ProviderHealth{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealth) ProtoMessage() {}

func (x *ProviderHealth) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealth.ProtoReflect.Descriptor instead.
func (*ProviderHealth) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderHealth) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *ProviderHealth) GetStatus() HealthStatus {
	if x != nil {
		return x.Status
	}
	return HealthStatus_HEALTH_UNKNOWN
}

func (x *ProviderHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProviderHealth) GetLastChecked() *timestamppb.Timestamp {
	if x != nil {
		return x.LastChecked
	}
	return nil
}

func (x *ProviderHealth) GetResponseTime() *durationpb.Duration {
	if x != nil {
		return x.ResponseTime
	}
	return nil
}

type Usage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Model           string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	RequestCount    int64                  `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	TokensUsed      int64                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	SuccessRate     float64                `protobuf:"fixed64,5,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgResponseTime *durationpb.Duration   `protobuf:"bytes,6,opt,name=avg_response_time,json=avgResponseTime,proto3" json:"avg_response_time,omitempty"`
	LastUsed        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *Usage) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Usage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Usage) GetRequestCount() int64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *Usage) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *Usage) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *Usage) GetAvgResponseTime() *durationpb.Duration {
	if x != nil {
		return x.AvgResponseTime
	}
	return nil
}

func (x *Usage) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

type AIError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ErrorType              `protobuf:"varint,1,opt,name=type,proto3,enum=ai.ErrorType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Provider      Provider               `protobuf:"varint,3,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Retryable     bool                   `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIError) Reset() {
	*x = AIError{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIError) ProtoMessage() {}

func (x *AIError) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIError.ProtoReflect.Descriptor instead.
func (*AIError) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *AIError) GetType() ErrorType {
	if x != nil {
		return x.Type
	}
	return ErrorType_ERROR_UNKNOWN
}

func (x *AIError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AIError) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *AIError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AIError) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *AIError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type GenerateSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *SQLRequest            `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSQLRequest) Reset() {
	*x = GenerateSQLRequest{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSQLRequest) ProtoMessage() {}

func (x *GenerateSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSQLRequest.ProtoReflect.Descriptor instead.
func (*GenerateSQLRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateSQLRequest) GetRequest() *SQLRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type GenerateSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *SQLResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error         *AIError               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateSQLResponse) Reset() {
	*x = GenerateSQLResponse{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateSQLResponse) ProtoMessage() {}

func (x *GenerateSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateSQLResponse.ProtoReflect.Descriptor instead.
func (*GenerateSQLResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateSQLResponse) GetResponse() *SQLResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *GenerateSQLResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type FixSQLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *SQLRequest            `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixSQLRequest) Reset() {
	*x = FixSQLRequest{}
	mi := &file_ai_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixSQLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixSQLRequest) ProtoMessage() {}

func (x *FixSQLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixSQLRequest.ProtoReflect.Descriptor instead.
func (*FixSQLRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{8}
}

func (x *FixSQLRequest) GetRequest() *SQLRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type FixSQLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *SQLResponse           `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Error         *AIError               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixSQLResponse) Reset() {
	*x = FixSQLResponse{}
	mi := &file_ai_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixSQLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixSQLResponse) ProtoMessage() {}

func (x *FixSQLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixSQLResponse.ProtoReflect.Descriptor instead.
func (*FixSQLResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{9}
}

func (x *FixSQLResponse) GetResponse() *SQLResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *FixSQLResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersRequest) Reset() {
	*x = GetProvidersRequest{}
	mi := &file_ai_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersRequest) ProtoMessage() {}

func (x *GetProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersRequest.ProtoReflect.Descriptor instead.
func (*GetProvidersRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{10}
}

type GetProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []Provider             `protobuf:"varint,1,rep,packed,name=providers,proto3,enum=ai.Provider" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProvidersResponse) Reset() {
	*x = GetProvidersResponse{}
	mi := &file_ai_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProvidersResponse) ProtoMessage() {}

func (x *GetProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProvidersResponse.ProtoReflect.Descriptor instead.
func (*GetProvidersResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetProvidersResponse) GetProviders() []Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type GetProviderHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderHealthRequest) Reset() {
	*x = GetProviderHealthRequest{}
	mi := &file_ai_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderHealthRequest) ProtoMessage() {}

func (x *GetProviderHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderHealthRequest.ProtoReflect.Descriptor instead.
func (*GetProviderHealthRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetProviderHealthRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

type ProviderHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *ProviderHealth        `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	Error         *AIError               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthResponse) Reset() {
	*x = ProviderHealthResponse{}
	mi := &file_ai_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthResponse) ProtoMessage() {}

func (x *ProviderHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthResponse.ProtoReflect.Descriptor instead.
func (*ProviderHealthResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{13}
}

func (x *ProviderHealthResponse) GetHealth() *ProviderHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *ProviderHealthResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetProviderModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderModelsRequest) Reset() {
	*x = GetProviderModelsRequest{}
	mi := &file_ai_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderModelsRequest) ProtoMessage() {}

func (x *GetProviderModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderModelsRequest.ProtoReflect.Descriptor instead.
func (*GetProviderModelsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetProviderModelsRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

type GetProviderModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Error         *AIError               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderModelsResponse) Reset() {
	*x = GetProviderModelsResponse{}
	mi := &file_ai_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderModelsResponse) ProtoMessage() {}

func (x *GetProviderModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderModelsResponse.ProtoReflect.Descriptor instead.
func (*GetProviderModelsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetProviderModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *GetProviderModelsResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type TestProviderRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Provider Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"`
	// Types that are valid to be assigned to Config:
	//
	//	*TestProviderRequest_OpenaiConfig
	//	*TestProviderRequest_AnthropicConfig
	//	*TestProviderRequest_OllamaConfig
	//	*TestProviderRequest_HuggingfaceConfig
	Config        isTestProviderRequest_Config `protobuf_oneof:"config"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderRequest) Reset() {
	*x = TestProviderRequest{}
	mi := &file_ai_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderRequest) ProtoMessage() {}

func (x *TestProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderRequest.ProtoReflect.Descriptor instead.
func (*TestProviderRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{16}
}

func (x *TestProviderRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *TestProviderRequest) GetConfig() isTestProviderRequest_Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *TestProviderRequest) GetOpenaiConfig() *OpenAIConfig {
	if x != nil {
		if x, ok := x.Config.(*TestProviderRequest_OpenaiConfig); ok {
			return x.OpenaiConfig
		}
	}
	return nil
}

func (x *TestProviderRequest) GetAnthropicConfig() *AnthropicConfig {
	if x != nil {
		if x, ok := x.Config.(*TestProviderRequest_AnthropicConfig); ok {
			return x.AnthropicConfig
		}
	}
	return nil
}

func (x *TestProviderRequest) GetOllamaConfig() *OllamaConfig {
	if x != nil {
		if x, ok := x.Config.(*TestProviderRequest_OllamaConfig); ok {
			return x.OllamaConfig
		}
	}
	return nil
}

func (x *TestProviderRequest) GetHuggingfaceConfig() *HuggingFaceConfig {
	if x != nil {
		if x, ok := x.Config.(*TestProviderRequest_HuggingfaceConfig); ok {
			return x.HuggingfaceConfig
		}
	}
	return nil
}

type isTestProviderRequest_Config interface {
	isTestProviderRequest_Config()
}

type TestProviderRequest_OpenaiConfig struct {
	OpenaiConfig *OpenAIConfig `protobuf:"bytes,2,opt,name=openai_config,json=openaiConfig,proto3,oneof"`
}

type TestProviderRequest_AnthropicConfig struct {
	AnthropicConfig *AnthropicConfig `protobuf:"bytes,3,opt,name=anthropic_config,json=anthropicConfig,proto3,oneof"`
}

type TestProviderRequest_OllamaConfig struct {
	OllamaConfig *OllamaConfig `protobuf:"bytes,4,opt,name=ollama_config,json=ollamaConfig,proto3,oneof"`
}

type TestProviderRequest_HuggingfaceConfig struct {
	HuggingfaceConfig *HuggingFaceConfig `protobuf:"bytes,5,opt,name=huggingface_config,json=huggingfaceConfig,proto3,oneof"`
}

func (*TestProviderRequest_OpenaiConfig) isTestProviderRequest_Config() {}

func (*TestProviderRequest_AnthropicConfig) isTestProviderRequest_Config() {}

func (*TestProviderRequest_OllamaConfig) isTestProviderRequest_Config() {}

func (*TestProviderRequest_HuggingfaceConfig) isTestProviderRequest_Config() {}

type TestProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *AIError               `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestProviderResponse) Reset() {
	*x = TestProviderResponse{}
	mi := &file_ai_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProviderResponse) ProtoMessage() {}

func (x *TestProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProviderResponse.ProtoReflect.Descriptor instead.
func (*TestProviderResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{17}
}

func (x *TestProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestProviderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestProviderResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      Provider               `protobuf:"varint,1,opt,name=provider,proto3,enum=ai.Provider" json:"provider,omitempty"` // If empty, return all providers
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatsRequest) Reset() {
	*x = GetUsageStatsRequest{}
	mi := &file_ai_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsRequest) ProtoMessage() {}

func (x *GetUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetUsageStatsRequest) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

type GetUsageStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsageStats    map[string]*Usage      `protobuf:"bytes,1,rep,name=usage_stats,json=usageStats,proto3" json:"usage_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key is provider name
	Error         *AIError               `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageStatsResponse) Reset() {
	*x = GetUsageStatsResponse{}
	mi := &file_ai_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageStatsResponse) ProtoMessage() {}

func (x *GetUsageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUsageStatsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetUsageStatsResponse) GetUsageStats() map[string]*Usage {
	if x != nil {
		return x.UsageStats
	}
	return nil
}

func (x *GetUsageStatsResponse) GetError() *AIError {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_ai_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{20}
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AIConfig              `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_ai_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetConfigResponse) GetConfig() *AIConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Configuration messages
type AIConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DefaultProvider Provider               `protobuf:"varint,1,opt,name=default_provider,json=defaultProvider,proto3,enum=ai.Provider" json:"default_provider,omitempty"`
	MaxTokens       int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature     float64                `protobuf:"fixed64,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	RequestTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	RateLimitPerMin int32                  `protobuf:"varint,5,opt,name=rate_limit_per_min,json=rateLimitPerMin,proto3" json:"rate_limit_per_min,omitempty"`
	Openai          *OpenAIConfig          `protobuf:"bytes,6,opt,name=openai,proto3" json:"openai,omitempty"`
	Anthropic       *AnthropicConfig       `protobuf:"bytes,7,opt,name=anthropic,proto3" json:"anthropic,omitempty"`
	Ollama          *OllamaConfig          `protobuf:"bytes,8,opt,name=ollama,proto3" json:"ollama,omitempty"`
	Huggingface     *HuggingFaceConfig     `protobuf:"bytes,9,opt,name=huggingface,proto3" json:"huggingface,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AIConfig) Reset() {
	*x = AIConfig{}
	mi := &file_ai_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIConfig) ProtoMessage() {}

func (x *AIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIConfig.ProtoReflect.Descriptor instead.
func (*AIConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{22}
}

func (x *AIConfig) GetDefaultProvider() Provider {
	if x != nil {
		return x.DefaultProvider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *AIConfig) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *AIConfig) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AIConfig) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *AIConfig) GetRateLimitPerMin() int32 {
	if x != nil {
		return x.RateLimitPerMin
	}
	return 0
}

func (x *AIConfig) GetOpenai() *OpenAIConfig {
	if x != nil {
		return x.Openai
	}
	return nil
}

func (x *AIConfig) GetAnthropic() *AnthropicConfig {
	if x != nil {
		return x.Anthropic
	}
	return nil
}

func (x *AIConfig) GetOllama() *OllamaConfig {
	if x != nil {
		return x.Ollama
	}
	return nil
}

func (x *AIConfig) GetHuggingface() *HuggingFaceConfig {
	if x != nil {
		return x.Huggingface
	}
	return nil
}

type OpenAIConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // Should be empty in responses for security
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Models        []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Configured    bool                   `protobuf:"varint,5,opt,name=configured,proto3" json:"configured,omitempty"` // Indicates if provider is configured
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenAIConfig) Reset() {
	*x = OpenAIConfig{}
	mi := &file_ai_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenAIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenAIConfig) ProtoMessage() {}

func (x *OpenAIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenAIConfig.ProtoReflect.Descriptor instead.
func (*OpenAIConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{23}
}

func (x *OpenAIConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *OpenAIConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *OpenAIConfig) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *OpenAIConfig) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *OpenAIConfig) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type AnthropicConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"` // Should be empty in responses for security
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Models        []string               `protobuf:"bytes,4,rep,name=models,proto3" json:"models,omitempty"`
	Configured    bool                   `protobuf:"varint,5,opt,name=configured,proto3" json:"configured,omitempty"` // Indicates if provider is configured
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnthropicConfig) Reset() {
	*x = AnthropicConfig{}
	mi := &file_ai_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnthropicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnthropicConfig) ProtoMessage() {}

func (x *AnthropicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnthropicConfig.ProtoReflect.Descriptor instead.
func (*AnthropicConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{24}
}

func (x *AnthropicConfig) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AnthropicConfig) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AnthropicConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AnthropicConfig) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AnthropicConfig) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type OllamaConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Endpoint        string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Models          []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	PullTimeout     *durationpb.Duration   `protobuf:"bytes,3,opt,name=pull_timeout,json=pullTimeout,proto3" json:"pull_timeout,omitempty"`
	GenerateTimeout *durationpb.Duration   `protobuf:"bytes,4,opt,name=generate_timeout,json=generateTimeout,proto3" json:"generate_timeout,omitempty"`
	AutoPullModels  bool                   `protobuf:"varint,5,opt,name=auto_pull_models,json=autoPullModels,proto3" json:"auto_pull_models,omitempty"`
	Configured      bool                   `protobuf:"varint,6,opt,name=configured,proto3" json:"configured,omitempty"` // Indicates if provider is configured
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OllamaConfig) Reset() {
	*x = OllamaConfig{}
	mi := &file_ai_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OllamaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OllamaConfig) ProtoMessage() {}

func (x *OllamaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OllamaConfig.ProtoReflect.Descriptor instead.
func (*OllamaConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{25}
}

func (x *OllamaConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *OllamaConfig) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *OllamaConfig) GetPullTimeout() *durationpb.Duration {
	if x != nil {
		return x.PullTimeout
	}
	return nil
}

func (x *OllamaConfig) GetGenerateTimeout() *durationpb.Duration {
	if x != nil {
		return x.GenerateTimeout
	}
	return nil
}

func (x *OllamaConfig) GetAutoPullModels() bool {
	if x != nil {
		return x.AutoPullModels
	}
	return false
}

func (x *OllamaConfig) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

type HuggingFaceConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Endpoint         string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Models           []string               `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	PullTimeout      *durationpb.Duration   `protobuf:"bytes,3,opt,name=pull_timeout,json=pullTimeout,proto3" json:"pull_timeout,omitempty"`
	GenerateTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=generate_timeout,json=generateTimeout,proto3" json:"generate_timeout,omitempty"`
	AutoPullModels   bool                   `protobuf:"varint,5,opt,name=auto_pull_models,json=autoPullModels,proto3" json:"auto_pull_models,omitempty"`
	RecommendedModel string                 `protobuf:"bytes,6,opt,name=recommended_model,json=recommendedModel,proto3" json:"recommended_model,omitempty"`
	Configured       bool                   `protobuf:"varint,7,opt,name=configured,proto3" json:"configured,omitempty"` // Indicates if provider is configured
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HuggingFaceConfig) Reset() {
	*x = HuggingFaceConfig{}
	mi := &file_ai_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuggingFaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuggingFaceConfig) ProtoMessage() {}

func (x *HuggingFaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuggingFaceConfig.ProtoReflect.Descriptor instead.
func (*HuggingFaceConfig) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{26}
}

func (x *HuggingFaceConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *HuggingFaceConfig) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *HuggingFaceConfig) GetPullTimeout() *durationpb.Duration {
	if x != nil {
		return x.PullTimeout
	}
	return nil
}

func (x *HuggingFaceConfig) GetGenerateTimeout() *durationpb.Duration {
	if x != nil {
		return x.GenerateTimeout
	}
	return nil
}

func (x *HuggingFaceConfig) GetAutoPullModels() bool {
	if x != nil {
		return x.AutoPullModels
	}
	return false
}

func (x *HuggingFaceConfig) GetRecommendedModel() string {
	if x != nil {
		return x.RecommendedModel
	}
	return ""
}

func (x *HuggingFaceConfig) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\x02ai\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xdc\x02\n" +
	"\n" +
	"SQLRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema\x12(\n" +
	"\bprovider\x18\x05 \x01(\x0e2\f.ai.ProviderR\bprovider\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\a \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\b \x01(\x01R\vtemperature\x125\n" +
	"\acontext\x18\t \x03(\v2\x1b.ai.SQLRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x03\n" +
	"\vSQLResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\x12(\n" +
	"\bprovider\x18\x06 \x01(\x0e2\f.ai.ProviderR\bprovider\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\x12\x1f\n" +
	"\vtokens_used\x18\b \x01(\x05R\n" +
	"tokensUsed\x128\n" +
	"\n" +
	"time_taken\x18\t \x01(\v2\x19.google.protobuf.DurationR\ttimeTaken\x129\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2\x1d.ai.SQLResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.ai.ProviderR\bprovider\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\"\n" +
	"\fcapabilities\x18\x06 \x03(\tR\fcapabilities\x127\n" +
	"\bmetadata\x18\a \x03(\v2\x1b.ai.ModelInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\x0eProviderHealth\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.ai.HealthStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12=\n" +
	"\flast_checked\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastChecked\x12>\n" +
	"\rresponse_time\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fresponseTime\"\xb0\x02\n" +
	"\x05Usage\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x03R\frequestCount\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x03R\n" +
	"tokensUsed\x12!\n" +
	"\fsuccess_rate\x18\x05 \x01(\x01R\vsuccessRate\x12E\n" +
	"\x11avg_response_time\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\x0favgResponseTime\x127\n" +
	"\tlast_used\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\"\x92\x02\n" +
	"\aAIError\x12!\n" +
	"\x04type\x18\x01 \x01(\x0e2\r.ai.ErrorTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\bprovider\x18\x03 \x01(\x0e2\f.ai.ProviderR\bprovider\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x122\n" +
	"\adetails\x18\x05 \x03(\v2\x18.ai.AIError.DetailsEntryR\adetails\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x12GenerateSQLRequest\x12(\n" +
	"\arequest\x18\x01 \x01(\v2\x0e.ai.SQLRequestR\arequest\"e\n" +
	"\x13GenerateSQLResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.ai.SQLResponseR\bresponse\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ai.AIErrorR\x05error\"9\n" +
	"\rFixSQLRequest\x12(\n" +
	"\arequest\x18\x01 \x01(\v2\x0e.ai.SQLRequestR\arequest\"`\n" +
	"\x0eFixSQLResponse\x12+\n" +
	"\bresponse\x18\x01 \x01(\v2\x0f.ai.SQLResponseR\bresponse\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ai.AIErrorR\x05error\"\x15\n" +
	"\x13GetProvidersRequest\"B\n" +
	"\x14GetProvidersResponse\x12*\n" +
	"\tproviders\x18\x01 \x03(\x0e2\f.ai.ProviderR\tproviders\"D\n" +
	"\x18GetProviderHealthRequest\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\"g\n" +
	"\x16ProviderHealthResponse\x12*\n" +
	"\x06health\x18\x01 \x01(\v2\x12.ai.ProviderHealthR\x06health\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ai.AIErrorR\x05error\"D\n" +
	"\x18GetProviderModelsRequest\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\"e\n" +
	"\x19GetProviderModelsResponse\x12%\n" +
	"\x06models\x18\x01 \x03(\v2\r.ai.ModelInfoR\x06models\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ai.AIErrorR\x05error\"\xc5\x02\n" +
	"\x13TestProviderRequest\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\x127\n" +
	"\ropenai_config\x18\x02 \x01(\v2\x10.ai.OpenAIConfigH\x00R\fopenaiConfig\x12@\n" +
	"\x10anthropic_config\x18\x03 \x01(\v2\x13.ai.AnthropicConfigH\x00R\x0fanthropicConfig\x127\n" +
	"\rollama_config\x18\x04 \x01(\v2\x10.ai.OllamaConfigH\x00R\follamaConfig\x12F\n" +
	"\x12huggingface_config\x18\x05 \x01(\v2\x15.ai.HuggingFaceConfigH\x00R\x11huggingfaceConfigB\b\n" +
	"\x06config\"m\n" +
	"\x14TestProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\x05error\x18\x03 \x01(\v2\v.ai.AIErrorR\x05error\"@\n" +
	"\x14GetUsageStatsRequest\x12(\n" +
	"\bprovider\x18\x01 \x01(\x0e2\f.ai.ProviderR\bprovider\"\xd0\x01\n" +
	"\x15GetUsageStatsResponse\x12J\n" +
	"\vusage_stats\x18\x01 \x03(\v2).ai.GetUsageStatsResponse.UsageStatsEntryR\n" +
	"usageStats\x12!\n" +
	"\x05error\x18\x02 \x01(\v2\v.ai.AIErrorR\x05error\x1aH\n" +
	"\x0fUsageStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.ai.UsageR\x05value:\x028\x01\"\x12\n" +
	"\x10GetConfigRequest\"9\n" +
	"\x11GetConfigResponse\x12$\n" +
	"\x06config\x18\x01 \x01(\v2\f.ai.AIConfigR\x06config\"\xb5\x03\n" +
	"\bAIConfig\x127\n" +
	"\x10default_provider\x18\x01 \x01(\x0e2\f.ai.ProviderR\x0fdefaultProvider\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x01R\vtemperature\x12B\n" +
	"\x0frequest_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x12+\n" +
	"\x12rate_limit_per_min\x18\x05 \x01(\x05R\x0frateLimitPerMin\x12(\n" +
	"\x06openai\x18\x06 \x01(\v2\x10.ai.OpenAIConfigR\x06openai\x121\n" +
	"\tanthropic\x18\a \x01(\v2\x13.ai.AnthropicConfigR\tanthropic\x12(\n" +
	"\x06ollama\x18\b \x01(\v2\x10.ai.OllamaConfigR\x06ollama\x127\n" +
	"\vhuggingface\x18\t \x01(\v2\x15.ai.HuggingFaceConfigR\vhuggingface\"\x91\x01\n" +
	"\fOpenAIConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x1e\n" +
	"\n" +
	"configured\x18\x05 \x01(\bR\n" +
	"configured\"\x97\x01\n" +
	"\x0fAnthropicConfig\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06models\x18\x04 \x03(\tR\x06models\x12\x1e\n" +
	"\n" +
	"configured\x18\x05 \x01(\bR\n" +
	"configured\"\x90\x02\n" +
	"\fOllamaConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12<\n" +
	"\fpull_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vpullTimeout\x12D\n" +
	"\x10generate_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fgenerateTimeout\x12(\n" +
	"\x10auto_pull_models\x18\x05 \x01(\bR\x0eautoPullModels\x12\x1e\n" +
	"\n" +
	"configured\x18\x06 \x01(\bR\n" +
	"configured\"\xc2\x02\n" +
	"\x11HuggingFaceConfig\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x16\n" +
	"\x06models\x18\x02 \x03(\tR\x06models\x12<\n" +
	"\fpull_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vpullTimeout\x12D\n" +
	"\x10generate_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0fgenerateTimeout\x12(\n" +
	"\x10auto_pull_models\x18\x05 \x01(\bR\x0eautoPullModels\x12+\n" +
	"\x11recommended_model\x18\x06 \x01(\tR\x10recommendedModel\x12\x1e\n" +
	"\n" +
	"configured\x18\a \x01(\bR\n" +
	"configured*\x80\x01\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPROVIDER_OPENAI\x10\x01\x12\x16\n" +
	"\x12PROVIDER_ANTHROPIC\x10\x02\x12\x13\n" +
	"\x0fPROVIDER_OLLAMA\x10\x03\x12\x18\n" +
	"\x14PROVIDER_HUGGINGFACE\x10\x04*^\n" +
	"\fHealthStatus\x12\x12\n" +
	"\x0eHEALTH_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eHEALTH_HEALTHY\x10\x01\x12\x14\n" +
	"\x10HEALTH_UNHEALTHY\x10\x02\x12\x10\n" +
	"\fHEALTH_ERROR\x10\x03*\xa8\x01\n" +
	"\tErrorType\x12\x11\n" +
	"\rERROR_UNKNOWN\x10\x00\x12\x19\n" +
	"\x15ERROR_INVALID_REQUEST\x10\x01\x12\x18\n" +
	"\x14ERROR_PROVIDER_ERROR\x10\x02\x12\x16\n" +
	"\x12ERROR_CONFIG_ERROR\x10\x03\x12\x14\n" +
	"\x10ERROR_RATE_LIMIT\x10\x04\x12\x11\n" +
	"\rERROR_TIMEOUT\x10\x05\x12\x12\n" +
	"\x0eERROR_INTERNAL\x10\x062\xa3\x04\n" +
	"\tAIService\x12>\n" +
	"\vGenerateSQL\x12\x16.ai.GenerateSQLRequest\x1a\x17.ai.GenerateSQLResponse\x12/\n" +
	"\x06FixSQL\x12\x11.ai.FixSQLRequest\x1a\x12.ai.FixSQLResponse\x12A\n" +
	"\fGetProviders\x12\x17.ai.GetProvidersRequest\x1a\x18.ai.GetProvidersResponse\x12M\n" +
	"\x11GetProviderHealth\x12\x1c.ai.GetProviderHealthRequest\x1a\x1a.ai.ProviderHealthResponse\x12P\n" +
	"\x11GetProviderModels\x12\x1c.ai.GetProviderModelsRequest\x1a\x1d.ai.GetProviderModelsResponse\x12A\n" +
	"\fTestProvider\x12\x17.ai.TestProviderRequest\x1a\x18.ai.TestProviderResponse\x12D\n" +
	"\rGetUsageStats\x12\x18.ai.GetUsageStatsRequest\x1a\x19.ai.GetUsageStatsResponse\x128\n" +
	"\tGetConfig\x12\x14.ai.GetConfigRequest\x1a\x15.ai.GetConfigResponseB,Z*github.com/sql-studio/backend-go/pkg/pb/aib\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_ai_service_proto_goTypes = []any{
	(Provider)(0),                     // 0: ai.Provider
	(HealthStatus)(0),                 // 1: ai.HealthStatus
	(ErrorType)(0),                    // 2: ai.ErrorType
	(*SQLRequest)(nil),                // 3: ai.SQLRequest
	(*SQLResponse)(nil),               // 4: ai.SQLResponse
	(*ModelInfo)(nil),                 // 5: ai.ModelInfo
	(*ProviderHealth)(nil),            // 6: ai.ProviderHealth
	(*Usage)(nil),                     // 7: ai.Usage
	(*AIError)(nil),                   // 8: ai.AIError
	(*GenerateSQLRequest)(nil),        // 9: ai.GenerateSQLRequest
	(*GenerateSQLResponse)(nil),       // 10: ai.GenerateSQLResponse
	(*FixSQLRequest)(nil),             // 11: ai.FixSQLRequest
	(*FixSQLResponse)(nil),            // 12: ai.FixSQLResponse
	(*GetProvidersRequest)(nil),       // 13: ai.GetProvidersRequest
	(*GetProvidersResponse)(nil),      // 14: ai.GetProvidersResponse
	(*GetProviderHealthRequest)(nil),  // 15: ai.GetProviderHealthRequest
	(*ProviderHealthResponse)(nil),    // 16: ai.ProviderHealthResponse
	(*GetProviderModelsRequest)(nil),  // 17: ai.GetProviderModelsRequest
	(*GetProviderModelsResponse)(nil), // 18: ai.GetProviderModelsResponse
	(*TestProviderRequest)(nil),       // 19: ai.TestProviderRequest
	(*TestProviderResponse)(nil),      // 20: ai.TestProviderResponse
	(*GetUsageStatsRequest)(nil),      // 21: ai.GetUsageStatsRequest
	(*GetUsageStatsResponse)(nil),     // 22: ai.GetUsageStatsResponse
	(*GetConfigRequest)(nil),          // 23: ai.GetConfigRequest
	(*GetConfigResponse)(nil),         // 24: ai.GetConfigResponse
	(*AIConfig)(nil),                  // 25: ai.AIConfig
	(*OpenAIConfig)(nil),              // 26: ai.OpenAIConfig
	(*AnthropicConfig)(nil),           // 27: ai.AnthropicConfig
	(*OllamaConfig)(nil),              // 28: ai.OllamaConfig
	(*HuggingFaceConfig)(nil),         // 29: ai.HuggingFaceConfig
	nil,                               // 30: ai.SQLRequest.ContextEntry
	nil,                               // 31: ai.SQLResponse.MetadataEntry
	nil,                               // 32: ai.ModelInfo.MetadataEntry
	nil,                               // 33: ai.AIError.DetailsEntry
	nil,                               // 34: ai.GetUsageStatsResponse.UsageStatsEntry
	(*durationpb.Duration)(nil),       // 35: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 36: google.protobuf.Timestamp
}
var file_ai_service_proto_depIdxs = []int32{
	0,  // 0: ai.SQLRequest.provider:type_name -> ai.Provider
	30, // 1: ai.SQLRequest.context:type_name -> ai.SQLRequest.ContextEntry
	0,  // 2: ai.SQLResponse.provider:type_name -> ai.Provider
	35, // 3: ai.SQLResponse.time_taken:type_name -> google.protobuf.Duration
	31, // 4: ai.SQLResponse.metadata:type_name -> ai.SQLResponse.MetadataEntry
	0,  // 5: ai.ModelInfo.provider:type_name -> ai.Provider
	32, // 6: ai.ModelInfo.metadata:type_name -> ai.ModelInfo.MetadataEntry
	0,  // 7: ai.ProviderHealth.provider:type_name -> ai.Provider
	1,  // 8: ai.ProviderHealth.status:type_name -> ai.HealthStatus
	36, // 9: ai.ProviderHealth.last_checked:type_name -> google.protobuf.Timestamp
	35, // 10: ai.ProviderHealth.response_time:type_name -> google.protobuf.Duration
	0,  // 11: ai.Usage.provider:type_name -> ai.Provider
	35, // 12: ai.Usage.avg_response_time:type_name -> google.protobuf.Duration
	36, // 13: ai.Usage.last_used:type_name -> google.protobuf.Timestamp
	2,  // 14: ai.AIError.type:type_name -> ai.ErrorType
	0,  // 15: ai.AIError.provider:type_name -> ai.Provider
	33, // 16: ai.AIError.details:type_name -> ai.AIError.DetailsEntry
	3,  // 17: ai.GenerateSQLRequest.request:type_name -> ai.SQLRequest
	4,  // 18: ai.GenerateSQLResponse.response:type_name -> ai.SQLResponse
	8,  // 19: ai.GenerateSQLResponse.error:type_name -> ai.AIError
	3,  // 20: ai.FixSQLRequest.request:type_name -> ai.SQLRequest
	4,  // 21: ai.FixSQLResponse.response:type_name -> ai.SQLResponse
	8,  // 22: ai.FixSQLResponse.error:type_name -> ai.AIError
	0,  // 23: ai.GetProvidersResponse.providers:type_name -> ai.Provider
	0,  // 24: ai.GetProviderHealthRequest.provider:type_name -> ai.Provider
	6,  // 25: ai.ProviderHealthResponse.health:type_name -> ai.ProviderHealth
	8,  // 26: ai.ProviderHealthResponse.error:type_name -> ai.AIError
	0,  // 27: ai.GetProviderModelsRequest.provider:type_name -> ai.Provider
	5,  // 28: ai.GetProviderModelsResponse.models:type_name -> ai.ModelInfo
	8,  // 29: ai.GetProviderModelsResponse.error:type_name -> ai.AIError
	0,  // 30: ai.TestProviderRequest.provider:type_name -> ai.Provider
	26, // 31: ai.TestProviderRequest.openai_config:type_name -> ai.OpenAIConfig
	27, // 32: ai.TestProviderRequest.anthropic_config:type_name -> ai.AnthropicConfig
	28, // 33: ai.TestProviderRequest.ollama_config:type_name -> ai.OllamaConfig
	29, // 34: ai.TestProviderRequest.huggingface_config:type_name -> ai.HuggingFaceConfig
	8,  // 35: ai.TestProviderResponse.error:type_name -> ai.AIError
	0,  // 36: ai.GetUsageStatsRequest.provider:type_name -> ai.Provider
	34, // 37: ai.GetUsageStatsResponse.usage_stats:type_name -> ai.GetUsageStatsResponse.UsageStatsEntry
	8,  // 38: ai.GetUsageStatsResponse.error:type_name -> ai.AIError
	25, // 39: ai.GetConfigResponse.config:type_name -> ai.AIConfig
	0,  // 40: ai.AIConfig.default_provider:type_name -> ai.Provider
	35, // 41: ai.AIConfig.request_timeout:type_name -> google.protobuf.Duration
	26, // 42: ai.AIConfig.openai:type_name -> ai.OpenAIConfig
	27, // 43: ai.AIConfig.anthropic:type_name -> ai.AnthropicConfig
	28, // 44: ai.AIConfig.ollama:type_name -> ai.OllamaConfig
	29, // 45: ai.AIConfig.huggingface:type_name -> ai.HuggingFaceConfig
	35, // 46: ai.OllamaConfig.pull_timeout:type_name -> google.protobuf.Duration
	35, // 47: ai.OllamaConfig.generate_timeout:type_name -> google.protobuf.Duration
	35, // 48: ai.HuggingFaceConfig.pull_timeout:type_name -> google.protobuf.Duration
	35, // 49: ai.HuggingFaceConfig.generate_timeout:type_name -> google.protobuf.Duration
	7,  // 50: ai.GetUsageStatsResponse.UsageStatsEntry.value:type_name -> ai.Usage
	9,  // 51: ai.AIService.GenerateSQL:input_type -> ai.GenerateSQLRequest
	11, // 52: ai.AIService.FixSQL:input_type -> ai.FixSQLRequest
	13, // 53: ai.AIService.GetProviders:input_type -> ai.GetProvidersRequest
	15, // 54: ai.AIService.GetProviderHealth:input_type -> ai.GetProviderHealthRequest
	17, // 55: ai.AIService.GetProviderModels:input_type -> ai.GetProviderModelsRequest
	19, // 56: ai.AIService.TestProvider:input_type -> ai.TestProviderRequest
	21, // 57: ai.AIService.GetUsageStats:input_type -> ai.GetUsageStatsRequest
	23, // 58: ai.AIService.GetConfig:input_type -> ai.GetConfigRequest
	10, // 59: ai.AIService.GenerateSQL:output_type -> ai.GenerateSQLResponse
	12, // 60: ai.AIService.FixSQL:output_type -> ai.FixSQLResponse
	14, // 61: ai.AIService.GetProviders:output_type -> ai.GetProvidersResponse
	16, // 62: ai.AIService.GetProviderHealth:output_type -> ai.ProviderHealthResponse
	18, // 63: ai.AIService.GetProviderModels:output_type -> ai.GetProviderModelsResponse
	20, // 64: ai.AIService.TestProvider:output_type -> ai.TestProviderResponse
	22, // 65: ai.AIService.GetUsageStats:output_type -> ai.GetUsageStatsResponse
	24, // 66: ai.AIService.GetConfig:output_type -> ai.GetConfigResponse
	59, // [59:67] is the sub-list for method output_type
	51, // [51:59] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	file_ai_service_proto_msgTypes[16].OneofWrappers = []any{
		(*TestProviderRequest_OpenaiConfig)(nil),
		(*TestProviderRequest_AnthropicConfig)(nil),
		(*TestProviderRequest_OllamaConfig)(nil),
		(*TestProviderRequest_HuggingfaceConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		EnumInfos:         file_ai_service_proto_enumTypes,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
