// Code generated by scripts/generate-bindings-dispatcher.mjs. DO NOT EDIT.
// Regenerate with `make bindings` (runs after `wails3 generate bindings`).
//
// Lazy dispatcher over the wails per-service bindings: gives the frontend one
// ".../app" import surface that is test-safe (each service module is imported
// lazily, only when a binding is first called, not at module load) and reuses the
// validated per-service Call.ByID bindings.

type BindingResult = any

// Loaders return the per-service module namespace; typed as any because this
// dispatcher routes calls dynamically by method name.
const loaders: Record<string, () => Promise<any>> = {
  'catalogservice': () => import('./catalogservice.js'),
  'connectionservice': () => import('./connectionservice.js'),
  'queryservice': () => import('./queryservice.js'),
  'schemadiffservice': () => import('./schemadiffservice.js'),
  'storageservice': () => import('./storageservice.js'),
  'updateservice': () => import('./updateservice.js'),
  'wailsaiservice': () => import('./wailsaiservice.js'),
  'wailsalertservice': () => import('./wailsalertservice.js'),
  'wailsauthservice': () => import('./wailsauthservice.js'),
  'wailsfileservice': () => import('./wailsfileservice.js'),
  'wailskeyboardservice': () => import('./wailskeyboardservice.js'),
  'wailsnotebookservice': () => import('./wailsnotebookservice.js'),
  'wailsreportservice': () => import('./wailsreportservice.js'),
  'wailsrunbookservice': () => import('./wailsrunbookservice.js'),
}

const methodService: Record<string, string> = {
  AddKeyboardBinding: 'wailskeyboardservice',
  AssignTableSteward: 'catalogservice',
  CancelQueryStream: 'queryservice',
  CheckAlertNow: 'wailsalertservice',
  CheckBiometricAvailability: 'wailsauthservice',
  CheckForUpdates: 'updateservice',
  CheckStoredToken: 'wailsauthservice',
  ClearAIMemorySessions: 'wailsaiservice',
  ClearRecentFiles: 'wailsfileservice',
  CompareConnectionSchemas: 'schemadiffservice',
  CompareWithSnapshot: 'schemadiffservice',
  ConfigureAIProvider: 'wailsaiservice',
  CopyFile: 'wailsfileservice',
  CreateCatalogTag: 'catalogservice',
  CreateColumnCatalogEntry: 'catalogservice',
  CreateConnection: 'connectionservice',
  CreateDirectory: 'wailsfileservice',
  CreateSchemaSnapshot: 'schemadiffservice',
  CreateTableCatalogEntry: 'catalogservice',
  CreateTempFile: 'wailsfileservice',
  DeleteAIMemorySession: 'wailsaiservice',
  DeleteAlert: 'wailsalertservice',
  DeleteCatalogTag: 'catalogservice',
  DeleteFile: 'wailsfileservice',
  DeleteNotebook: 'wailsnotebookservice',
  DeletePassword: 'wailsfileservice',
  DeleteQueryRows: 'queryservice',
  DeleteReport: 'wailsreportservice',
  DeleteRunbook: 'wailsrunbookservice',
  DeleteSchemaSnapshot: 'schemadiffservice',
  DeleteSyntheticView: 'storageservice',
  DeleteTableCatalogEntry: 'catalogservice',
  DeleteWebAuthnCredential: 'wailsauthservice',
  DownloadAndInstall: 'updateservice',
  ExecuteMultiDatabaseQuery: 'queryservice',
  ExecuteQuery: 'queryservice',
  ExecuteQueryStream: 'queryservice',
  ExecuteReadOnlyQuery: 'wailsaiservice',
  ExecuteReadOnlyQueryWithPagination: 'wailsaiservice',
  ExecuteSyntheticQuery: 'storageservice',
  ExplainQuery: 'queryservice',
  ExportKeyboardBindings: 'wailskeyboardservice',
  FileExists: 'wailsfileservice',
  FinishWebAuthnAuthentication: 'wailsauthservice',
  FinishWebAuthnRegistration: 'wailsauthservice',
  FixSQLError: 'wailsaiservice',
  FixSQLErrorWithOptions: 'wailsaiservice',
  GenerateInsightBrief: 'wailsaiservice',
  GenerateMigrationSQL: 'schemadiffservice',
  GenerateMigrationSQLFromSnapshot: 'schemadiffservice',
  GenerateSQLFromNaturalLanguage: 'wailsaiservice',
  GenericChat: 'wailsaiservice',
  GetAIConfiguration: 'wailsaiservice',
  GetAIProviderStatus: 'wailsaiservice',
  GetAlert: 'wailsalertservice',
  GetAllKeyboardBindings: 'wailskeyboardservice',
  GetAppIcon: 'wailsfileservice',
  GetAppVersion: 'wailsfileservice',
  GetAvailableEnvironments: 'connectionservice',
  GetAvailableModels: 'wailsaiservice',
  GetCatalogStats: 'catalogservice',
  GetColumnCatalogEntry: 'catalogservice',
  GetConnectionCount: 'connectionservice',
  GetConnectionHealth: 'connectionservice',
  GetConnectionIDs: 'connectionservice',
  GetConnectionSchemaFull: 'queryservice',
  GetConnectionStats: 'connectionservice',
  GetCurrentVersion: 'updateservice',
  GetDarkIcon: 'wailsfileservice',
  GetDatabaseSchema: 'queryservice',
  GetDatabaseTypeInfo: 'connectionservice',
  GetDatabaseVersion: 'connectionservice',
  GetDownloadsPath: 'wailsfileservice',
  GetEditableMetadata: 'queryservice',
  GetFileInfo: 'wailsfileservice',
  GetHomePath: 'wailsfileservice',
  GetKeyboardBindingsByCategory: 'wailskeyboardservice',
  GetLightIcon: 'wailsfileservice',
  GetMultiConnectionSchema: 'queryservice',
  GetNotebook: 'wailsnotebookservice',
  GetOAuthURL: 'wailsauthservice',
  GetPassword: 'wailsfileservice',
  GetQuerySuggestions: 'wailsaiservice',
  GetRecentFiles: 'wailsfileservice',
  GetReport: 'wailsreportservice',
  GetRunbook: 'wailsrunbookservice',
  GetSchemaCacheStats: 'connectionservice',
  GetSchemaSnapshot: 'schemadiffservice',
  GetSchemas: 'queryservice',
  GetStoredUserInfo: 'wailsauthservice',
  GetSupportedDatabaseTypes: 'connectionservice',
  GetSyntheticSchema: 'storageservice',
  GetSyntheticView: 'storageservice',
  GetTableCatalogEntry: 'catalogservice',
  GetTableStructure: 'queryservice',
  GetTables: 'queryservice',
  GetTempDir: 'wailsfileservice',
  GetWorkspaceFiles: 'wailsfileservice',
  HandleKeyboardEvent: 'wailskeyboardservice',
  HasPassword: 'wailsfileservice',
  HasWebAuthnCredential: 'wailsauthservice',
  HealthCheckAll: 'connectionservice',
  ImportKeyboardBindings: 'wailskeyboardservice',
  InsertQueryRow: 'queryservice',
  InvalidateAllSchemas: 'connectionservice',
  InvalidateSchemaCache: 'connectionservice',
  ListAlerts: 'wailsalertservice',
  ListCatalogTags: 'catalogservice',
  ListColumnCatalogEntries: 'catalogservice',
  ListConnectionDatabases: 'connectionservice',
  ListConnections: 'connectionservice',
  ListNotebooks: 'wailsnotebookservice',
  ListReports: 'wailsreportservice',
  ListRunbooks: 'wailsrunbookservice',
  ListSchemaSnapshots: 'schemadiffservice',
  ListSyntheticViews: 'storageservice',
  ListTableCatalogEntries: 'catalogservice',
  LoadAIMemorySessions: 'wailsaiservice',
  Logout: 'wailsauthservice',
  MarkColumnAsPII: 'catalogservice',
  NotebookHistory: 'wailsnotebookservice',
  OnUrlOpen: 'wailsauthservice',
  OpenDownloadPage: 'updateservice',
  OpenEnvFileDialog: 'wailsfileservice',
  OpenFileDialog: 'wailsfileservice',
  OptimizeQuery: 'wailsaiservice',
  ParseQueryConnections: 'queryservice',
  ReadFile: 'wailsfileservice',
  RecallAIMemorySessions: 'wailsaiservice',
  RefreshSchema: 'connectionservice',
  RemoveConnection: 'connectionservice',
  RemoveFromRecentFiles: 'wailsfileservice',
  RemoveKeyboardBinding: 'wailskeyboardservice',
  ResetKeyboardBindings: 'wailskeyboardservice',
  RestartApp: 'updateservice',
  RunNotebook: 'wailsnotebookservice',
  RunReport: 'wailsreportservice',
  RunRunbook: 'wailsrunbookservice',
  RunbookHistory: 'wailsrunbookservice',
  SQLiteDeleteConnection: 'storageservice',
  SQLiteDeleteQuery: 'storageservice',
  SQLiteGetConnection: 'storageservice',
  SQLiteGetConnections: 'storageservice',
  SQLiteGetQueries: 'storageservice',
  SQLiteGetQuery: 'storageservice',
  SQLiteGetQueryHistory: 'storageservice',
  SQLiteGetSetting: 'storageservice',
  SQLiteSaveConnection: 'storageservice',
  SQLiteSaveQuery: 'storageservice',
  SQLiteSaveQueryHistory: 'storageservice',
  SQLiteSetSetting: 'storageservice',
  SaveAIMemorySessions: 'wailsaiservice',
  SaveAlert: 'wailsalertservice',
  SaveConnection: 'connectionservice',
  SaveFileDialog: 'wailsfileservice',
  SaveNotebook: 'wailsnotebookservice',
  SaveReport: 'wailsreportservice',
  SaveRunbook: 'wailsrunbookservice',
  SaveSyntheticView: 'storageservice',
  SaveToDownloads: 'wailsfileservice',
  SearchCatalog: 'catalogservice',
  SetAlertEnabled: 'wailsalertservice',
  SetApp: 'updateservice',
  SetStore: 'wailsalertservice',
  ShowErrorDialog: 'wailsfileservice',
  ShowInfoDialog: 'wailsfileservice',
  ShowNotification: 'wailsfileservice',
  ShowQuestionDialog: 'wailsfileservice',
  Start: 'wailsalertservice',
  StartClaudeCodeLogin: 'wailsaiservice',
  StartCodexLogin: 'wailsaiservice',
  StartWebAuthnAuthentication: 'wailsauthservice',
  StartWebAuthnRegistration: 'wailsauthservice',
  Stop: 'wailsalertservice',
  StorageCompleteMigration: 'storageservice',
  StorageImportConnections: 'storageservice',
  StorageImportHistory: 'storageservice',
  StorageImportPreferences: 'storageservice',
  StorageImportQueries: 'storageservice',
  StorageMigrationStatus: 'storageservice',
  StorePassword: 'wailsfileservice',
  StreamAIQueryAgent: 'wailsaiservice',
  SuggestVisualization: 'wailsaiservice',
  SwitchConnectionDatabase: 'connectionservice',
  SyncCatalogFromConnection: 'catalogservice',
  TestAIProvider: 'wailsaiservice',
  TestAnthropicConnection: 'wailsaiservice',
  TestClaudeCodeConnection: 'wailsaiservice',
  TestCodexConnection: 'wailsaiservice',
  TestConnection: 'connectionservice',
  TestHuggingFaceConnection: 'wailsaiservice',
  TestOllamaConnection: 'wailsaiservice',
  TestOpenAIConnection: 'wailsaiservice',
  UpdateColumnCatalogEntry: 'catalogservice',
  UpdateQueryRow: 'queryservice',
  UpdateTableCatalogEntry: 'catalogservice',
  ValidateMultiQuery: 'queryservice',
  WriteFile: 'wailsfileservice',
}

function makeBinding(method: string): (...args: unknown[]) => Promise<BindingResult> {
  return async (...args: unknown[]) => {
    const file = methodService[method]
    const load = loaders[file]
    if (!load) {
      throw new Error(`Wails binding "${method}" has no registered service module`)
    }
    const mod = await load()
    const fn = mod[method]
    if (typeof fn !== 'function') {
      throw new Error(`Wails binding "${method}" not found in ${file}`)
    }
    return fn(...args)
  }
}

export const AddKeyboardBinding = makeBinding('AddKeyboardBinding')
export const AssignTableSteward = makeBinding('AssignTableSteward')
export const CancelQueryStream = makeBinding('CancelQueryStream')
export const CheckAlertNow = makeBinding('CheckAlertNow')
export const CheckBiometricAvailability = makeBinding('CheckBiometricAvailability')
export const CheckForUpdates = makeBinding('CheckForUpdates')
export const CheckStoredToken = makeBinding('CheckStoredToken')
export const ClearAIMemorySessions = makeBinding('ClearAIMemorySessions')
export const ClearRecentFiles = makeBinding('ClearRecentFiles')
export const CompareConnectionSchemas = makeBinding('CompareConnectionSchemas')
export const CompareWithSnapshot = makeBinding('CompareWithSnapshot')
export const ConfigureAIProvider = makeBinding('ConfigureAIProvider')
export const CopyFile = makeBinding('CopyFile')
export const CreateCatalogTag = makeBinding('CreateCatalogTag')
export const CreateColumnCatalogEntry = makeBinding('CreateColumnCatalogEntry')
export const CreateConnection = makeBinding('CreateConnection')
export const CreateDirectory = makeBinding('CreateDirectory')
export const CreateSchemaSnapshot = makeBinding('CreateSchemaSnapshot')
export const CreateTableCatalogEntry = makeBinding('CreateTableCatalogEntry')
export const CreateTempFile = makeBinding('CreateTempFile')
export const DeleteAIMemorySession = makeBinding('DeleteAIMemorySession')
export const DeleteAlert = makeBinding('DeleteAlert')
export const DeleteCatalogTag = makeBinding('DeleteCatalogTag')
export const DeleteFile = makeBinding('DeleteFile')
export const DeleteNotebook = makeBinding('DeleteNotebook')
export const DeletePassword = makeBinding('DeletePassword')
export const DeleteQueryRows = makeBinding('DeleteQueryRows')
export const DeleteReport = makeBinding('DeleteReport')
export const DeleteRunbook = makeBinding('DeleteRunbook')
export const DeleteSchemaSnapshot = makeBinding('DeleteSchemaSnapshot')
export const DeleteSyntheticView = makeBinding('DeleteSyntheticView')
export const DeleteTableCatalogEntry = makeBinding('DeleteTableCatalogEntry')
export const DeleteWebAuthnCredential = makeBinding('DeleteWebAuthnCredential')
export const DownloadAndInstall = makeBinding('DownloadAndInstall')
export const ExecuteMultiDatabaseQuery = makeBinding('ExecuteMultiDatabaseQuery')
export const ExecuteQuery = makeBinding('ExecuteQuery')
export const ExecuteQueryStream = makeBinding('ExecuteQueryStream')
export const ExecuteReadOnlyQuery = makeBinding('ExecuteReadOnlyQuery')
export const ExecuteReadOnlyQueryWithPagination = makeBinding('ExecuteReadOnlyQueryWithPagination')
export const ExecuteSyntheticQuery = makeBinding('ExecuteSyntheticQuery')
export const ExplainQuery = makeBinding('ExplainQuery')
export const ExportKeyboardBindings = makeBinding('ExportKeyboardBindings')
export const FileExists = makeBinding('FileExists')
export const FinishWebAuthnAuthentication = makeBinding('FinishWebAuthnAuthentication')
export const FinishWebAuthnRegistration = makeBinding('FinishWebAuthnRegistration')
export const FixSQLError = makeBinding('FixSQLError')
export const FixSQLErrorWithOptions = makeBinding('FixSQLErrorWithOptions')
export const GenerateInsightBrief = makeBinding('GenerateInsightBrief')
export const GenerateMigrationSQL = makeBinding('GenerateMigrationSQL')
export const GenerateMigrationSQLFromSnapshot = makeBinding('GenerateMigrationSQLFromSnapshot')
export const GenerateSQLFromNaturalLanguage = makeBinding('GenerateSQLFromNaturalLanguage')
export const GenericChat = makeBinding('GenericChat')
export const GetAIConfiguration = makeBinding('GetAIConfiguration')
export const GetAIProviderStatus = makeBinding('GetAIProviderStatus')
export const GetAlert = makeBinding('GetAlert')
export const GetAllKeyboardBindings = makeBinding('GetAllKeyboardBindings')
export const GetAppIcon = makeBinding('GetAppIcon')
export const GetAppVersion = makeBinding('GetAppVersion')
export const GetAvailableEnvironments = makeBinding('GetAvailableEnvironments')
export const GetAvailableModels = makeBinding('GetAvailableModels')
export const GetCatalogStats = makeBinding('GetCatalogStats')
export const GetColumnCatalogEntry = makeBinding('GetColumnCatalogEntry')
export const GetConnectionCount = makeBinding('GetConnectionCount')
export const GetConnectionHealth = makeBinding('GetConnectionHealth')
export const GetConnectionIDs = makeBinding('GetConnectionIDs')
export const GetConnectionSchemaFull = makeBinding('GetConnectionSchemaFull')
export const GetConnectionStats = makeBinding('GetConnectionStats')
export const GetCurrentVersion = makeBinding('GetCurrentVersion')
export const GetDarkIcon = makeBinding('GetDarkIcon')
export const GetDatabaseSchema = makeBinding('GetDatabaseSchema')
export const GetDatabaseTypeInfo = makeBinding('GetDatabaseTypeInfo')
export const GetDatabaseVersion = makeBinding('GetDatabaseVersion')
export const GetDownloadsPath = makeBinding('GetDownloadsPath')
export const GetEditableMetadata = makeBinding('GetEditableMetadata')
export const GetFileInfo = makeBinding('GetFileInfo')
export const GetHomePath = makeBinding('GetHomePath')
export const GetKeyboardBindingsByCategory = makeBinding('GetKeyboardBindingsByCategory')
export const GetLightIcon = makeBinding('GetLightIcon')
export const GetMultiConnectionSchema = makeBinding('GetMultiConnectionSchema')
export const GetNotebook = makeBinding('GetNotebook')
export const GetOAuthURL = makeBinding('GetOAuthURL')
export const GetPassword = makeBinding('GetPassword')
export const GetQuerySuggestions = makeBinding('GetQuerySuggestions')
export const GetRecentFiles = makeBinding('GetRecentFiles')
export const GetReport = makeBinding('GetReport')
export const GetRunbook = makeBinding('GetRunbook')
export const GetSchemaCacheStats = makeBinding('GetSchemaCacheStats')
export const GetSchemaSnapshot = makeBinding('GetSchemaSnapshot')
export const GetSchemas = makeBinding('GetSchemas')
export const GetStoredUserInfo = makeBinding('GetStoredUserInfo')
export const GetSupportedDatabaseTypes = makeBinding('GetSupportedDatabaseTypes')
export const GetSyntheticSchema = makeBinding('GetSyntheticSchema')
export const GetSyntheticView = makeBinding('GetSyntheticView')
export const GetTableCatalogEntry = makeBinding('GetTableCatalogEntry')
export const GetTableStructure = makeBinding('GetTableStructure')
export const GetTables = makeBinding('GetTables')
export const GetTempDir = makeBinding('GetTempDir')
export const GetWorkspaceFiles = makeBinding('GetWorkspaceFiles')
export const HandleKeyboardEvent = makeBinding('HandleKeyboardEvent')
export const HasPassword = makeBinding('HasPassword')
export const HasWebAuthnCredential = makeBinding('HasWebAuthnCredential')
export const HealthCheckAll = makeBinding('HealthCheckAll')
export const ImportKeyboardBindings = makeBinding('ImportKeyboardBindings')
export const InsertQueryRow = makeBinding('InsertQueryRow')
export const InvalidateAllSchemas = makeBinding('InvalidateAllSchemas')
export const InvalidateSchemaCache = makeBinding('InvalidateSchemaCache')
export const ListAlerts = makeBinding('ListAlerts')
export const ListCatalogTags = makeBinding('ListCatalogTags')
export const ListColumnCatalogEntries = makeBinding('ListColumnCatalogEntries')
export const ListConnectionDatabases = makeBinding('ListConnectionDatabases')
export const ListConnections = makeBinding('ListConnections')
export const ListNotebooks = makeBinding('ListNotebooks')
export const ListReports = makeBinding('ListReports')
export const ListRunbooks = makeBinding('ListRunbooks')
export const ListSchemaSnapshots = makeBinding('ListSchemaSnapshots')
export const ListSyntheticViews = makeBinding('ListSyntheticViews')
export const ListTableCatalogEntries = makeBinding('ListTableCatalogEntries')
export const LoadAIMemorySessions = makeBinding('LoadAIMemorySessions')
export const Logout = makeBinding('Logout')
export const MarkColumnAsPII = makeBinding('MarkColumnAsPII')
export const NotebookHistory = makeBinding('NotebookHistory')
export const OnUrlOpen = makeBinding('OnUrlOpen')
export const OpenDownloadPage = makeBinding('OpenDownloadPage')
export const OpenEnvFileDialog = makeBinding('OpenEnvFileDialog')
export const OpenFileDialog = makeBinding('OpenFileDialog')
export const OptimizeQuery = makeBinding('OptimizeQuery')
export const ParseQueryConnections = makeBinding('ParseQueryConnections')
export const ReadFile = makeBinding('ReadFile')
export const RecallAIMemorySessions = makeBinding('RecallAIMemorySessions')
export const RefreshSchema = makeBinding('RefreshSchema')
export const RemoveConnection = makeBinding('RemoveConnection')
export const RemoveFromRecentFiles = makeBinding('RemoveFromRecentFiles')
export const RemoveKeyboardBinding = makeBinding('RemoveKeyboardBinding')
export const ResetKeyboardBindings = makeBinding('ResetKeyboardBindings')
export const RestartApp = makeBinding('RestartApp')
export const RunNotebook = makeBinding('RunNotebook')
export const RunReport = makeBinding('RunReport')
export const RunRunbook = makeBinding('RunRunbook')
export const RunbookHistory = makeBinding('RunbookHistory')
export const SQLiteDeleteConnection = makeBinding('SQLiteDeleteConnection')
export const SQLiteDeleteQuery = makeBinding('SQLiteDeleteQuery')
export const SQLiteGetConnection = makeBinding('SQLiteGetConnection')
export const SQLiteGetConnections = makeBinding('SQLiteGetConnections')
export const SQLiteGetQueries = makeBinding('SQLiteGetQueries')
export const SQLiteGetQuery = makeBinding('SQLiteGetQuery')
export const SQLiteGetQueryHistory = makeBinding('SQLiteGetQueryHistory')
export const SQLiteGetSetting = makeBinding('SQLiteGetSetting')
export const SQLiteSaveConnection = makeBinding('SQLiteSaveConnection')
export const SQLiteSaveQuery = makeBinding('SQLiteSaveQuery')
export const SQLiteSaveQueryHistory = makeBinding('SQLiteSaveQueryHistory')
export const SQLiteSetSetting = makeBinding('SQLiteSetSetting')
export const SaveAIMemorySessions = makeBinding('SaveAIMemorySessions')
export const SaveAlert = makeBinding('SaveAlert')
export const SaveConnection = makeBinding('SaveConnection')
export const SaveFileDialog = makeBinding('SaveFileDialog')
export const SaveNotebook = makeBinding('SaveNotebook')
export const SaveReport = makeBinding('SaveReport')
export const SaveRunbook = makeBinding('SaveRunbook')
export const SaveSyntheticView = makeBinding('SaveSyntheticView')
export const SaveToDownloads = makeBinding('SaveToDownloads')
export const SearchCatalog = makeBinding('SearchCatalog')
export const SetAlertEnabled = makeBinding('SetAlertEnabled')
export const SetApp = makeBinding('SetApp')
export const SetStore = makeBinding('SetStore')
export const ShowErrorDialog = makeBinding('ShowErrorDialog')
export const ShowInfoDialog = makeBinding('ShowInfoDialog')
export const ShowNotification = makeBinding('ShowNotification')
export const ShowQuestionDialog = makeBinding('ShowQuestionDialog')
export const Start = makeBinding('Start')
export const StartClaudeCodeLogin = makeBinding('StartClaudeCodeLogin')
export const StartCodexLogin = makeBinding('StartCodexLogin')
export const StartWebAuthnAuthentication = makeBinding('StartWebAuthnAuthentication')
export const StartWebAuthnRegistration = makeBinding('StartWebAuthnRegistration')
export const Stop = makeBinding('Stop')
export const StorageCompleteMigration = makeBinding('StorageCompleteMigration')
export const StorageImportConnections = makeBinding('StorageImportConnections')
export const StorageImportHistory = makeBinding('StorageImportHistory')
export const StorageImportPreferences = makeBinding('StorageImportPreferences')
export const StorageImportQueries = makeBinding('StorageImportQueries')
export const StorageMigrationStatus = makeBinding('StorageMigrationStatus')
export const StorePassword = makeBinding('StorePassword')
export const StreamAIQueryAgent = makeBinding('StreamAIQueryAgent')
export const SuggestVisualization = makeBinding('SuggestVisualization')
export const SwitchConnectionDatabase = makeBinding('SwitchConnectionDatabase')
export const SyncCatalogFromConnection = makeBinding('SyncCatalogFromConnection')
export const TestAIProvider = makeBinding('TestAIProvider')
export const TestAnthropicConnection = makeBinding('TestAnthropicConnection')
export const TestClaudeCodeConnection = makeBinding('TestClaudeCodeConnection')
export const TestCodexConnection = makeBinding('TestCodexConnection')
export const TestConnection = makeBinding('TestConnection')
export const TestHuggingFaceConnection = makeBinding('TestHuggingFaceConnection')
export const TestOllamaConnection = makeBinding('TestOllamaConnection')
export const TestOpenAIConnection = makeBinding('TestOpenAIConnection')
export const UpdateColumnCatalogEntry = makeBinding('UpdateColumnCatalogEntry')
export const UpdateQueryRow = makeBinding('UpdateQueryRow')
export const UpdateTableCatalogEntry = makeBinding('UpdateTableCatalogEntry')
export const ValidateMultiQuery = makeBinding('ValidateMultiQuery')
export const WriteFile = makeBinding('WriteFile')

export type JSONValue = string | number | boolean | null | JSONValue[] | { [key: string]: JSONValue }
export type JSONRecord = Record<string, JSONValue>
export type BindingObject = Record<string, unknown>
