// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CatalogService handles data catalog operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as catalog$0 from "./pkg/catalog/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AssignTableSteward assigns a steward to a table
 * @param {string} tableID
 * @param {string} userID
 * @returns {$CancellablePromise<void>}
 */
export function AssignTableSteward(tableID, userID) {
    return $Call.ByID(2871533907, tableID, userID);
}

/**
 * CreateCatalogTag creates a new custom tag
 * @param {catalog$0.CatalogTag | null} tag
 * @returns {$CancellablePromise<void>}
 */
export function CreateCatalogTag(tag) {
    return $Call.ByID(1831868915, tag);
}

/**
 * CreateColumnCatalogEntry creates a new column catalog entry
 * @param {catalog$0.ColumnCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function CreateColumnCatalogEntry(entry) {
    return $Call.ByID(3516402597, entry);
}

/**
 * CreateTableCatalogEntry creates a new table entry in the catalog
 * @param {catalog$0.TableCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function CreateTableCatalogEntry(entry) {
    return $Call.ByID(2199815167, entry);
}

/**
 * DeleteCatalogTag deletes a custom tag
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCatalogTag(id) {
    return $Call.ByID(3990439336, id);
}

/**
 * DeleteTableCatalogEntry deletes a table catalog entry
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTableCatalogEntry(id) {
    return $Call.ByID(1778001386, id);
}

/**
 * GetCatalogStats returns statistics about the catalog
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.CatalogStats | null>}
 */
export function GetCatalogStats(connectionID) {
    return $Call.ByID(3547469908, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetColumnCatalogEntry retrieves a column catalog entry
 * @param {string} tableID
 * @param {string} column
 * @returns {$CancellablePromise<catalog$0.ColumnCatalogEntry | null>}
 */
export function GetColumnCatalogEntry(tableID, column) {
    return $Call.ByID(3226829965, tableID, column).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTableCatalogEntry retrieves a table catalog entry
 * @param {string} connectionID
 * @param {string} schema
 * @param {string} table
 * @returns {$CancellablePromise<catalog$0.TableCatalogEntry | null>}
 */
export function GetTableCatalogEntry(connectionID, schema, table) {
    return $Call.ByID(3260243399, connectionID, schema, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListCatalogTags lists all tags for an organization
 * @param {string | null} orgID
 * @returns {$CancellablePromise<(catalog$0.CatalogTag | null)[]>}
 */
export function ListCatalogTags(orgID) {
    return $Call.ByID(2920466552, orgID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ListColumnCatalogEntries lists all column entries for a table
 * @param {string} tableID
 * @returns {$CancellablePromise<(catalog$0.ColumnCatalogEntry | null)[]>}
 */
export function ListColumnCatalogEntries(tableID) {
    return $Call.ByID(3259698657, tableID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ListTableCatalogEntries lists all table entries for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<(catalog$0.TableCatalogEntry | null)[]>}
 */
export function ListTableCatalogEntries(connectionID) {
    return $Call.ByID(1487031295, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * MarkColumnAsPII marks a column as containing PII
 * @param {string} tableID
 * @param {string} columnName
 * @param {string} piiType
 * @param {number} confidence
 * @returns {$CancellablePromise<void>}
 */
export function MarkColumnAsPII(tableID, columnName, piiType, confidence) {
    return $Call.ByID(2762590261, tableID, columnName, piiType, confidence);
}

/**
 * SearchCatalog searches the catalog for tables and columns
 * @param {string} query
 * @param {catalog$0.SearchFilters | null} filters
 * @returns {$CancellablePromise<catalog$0.SearchResults | null>}
 */
export function SearchCatalog(query, filters) {
    return $Call.ByID(461360161, query, filters).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * SyncCatalogFromConnection syncs the catalog with the actual database schema
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.CatalogSyncResult | null>}
 */
export function SyncCatalogFromConnection(connectionID) {
    return $Call.ByID(2244516948, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * UpdateColumnCatalogEntry updates a column catalog entry
 * @param {catalog$0.ColumnCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function UpdateColumnCatalogEntry(entry) {
    return $Call.ByID(3880007192, entry);
}

/**
 * UpdateTableCatalogEntry updates a table catalog entry
 * @param {catalog$0.TableCatalogEntry | null} entry
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTableCatalogEntry(entry) {
    return $Call.ByID(3506534348, entry);
}

// Private type creation functions
const $$createType0 = $models.CatalogStats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = catalog$0.ColumnCatalogEntry.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = catalog$0.TableCatalogEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = catalog$0.CatalogTag.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $Create.Array($$createType3);
const $$createType10 = $Create.Array($$createType5);
const $$createType11 = catalog$0.SearchResults.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = $models.CatalogSyncResult.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
