// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService handles all database connection operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "./pkg/database/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConnection creates a new database connection
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<$models.ConnectionInfo | null>}
 */
export function CreateConnection(req) {
    return $Call.ByID(3604157573, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAvailableEnvironments returns all unique environment tags across connections
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableEnvironments() {
    return $Call.ByID(71285460).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetConnectionCount returns the number of active database connections
 * @returns {$CancellablePromise<number>}
 */
export function GetConnectionCount() {
    return $Call.ByID(1410668602);
}

/**
 * GetConnectionHealth returns the health status of a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.HealthStatus | null>}
 */
export function GetConnectionHealth(connectionID) {
    return $Call.ByID(1803982829, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetConnectionIDs returns a list of all connection IDs
 * @returns {$CancellablePromise<string[]>}
 */
export function GetConnectionIDs() {
    return $Call.ByID(2806462223).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetConnectionStats returns connection pool statistics
 * @returns {$CancellablePromise<{ [_ in string]?: database$0.PoolStats }>}
 */
export function GetConnectionStats() {
    return $Call.ByID(114194806).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetDatabaseTypeInfo returns information about a database type
 * @param {string} dbType
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetDatabaseTypeInfo(dbType) {
    return $Call.ByID(2893133902, dbType).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetDatabaseVersion returns the database version
 * @param {string} connectionID
 * @returns {$CancellablePromise<string>}
 */
export function GetDatabaseVersion(connectionID) {
    return $Call.ByID(2776337458, connectionID);
}

/**
 * GetSchemaCacheStats returns statistics about the schema cache
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSchemaCacheStats() {
    return $Call.ByID(1242619645).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetSupportedDatabaseTypes returns supported database types
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSupportedDatabaseTypes() {
    return $Call.ByID(3162222467).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * HealthCheckAll performs health checks on all connections
 * @returns {$CancellablePromise<{ [_ in string]?: $models.HealthStatus | null }>}
 */
export function HealthCheckAll() {
    return $Call.ByID(1444971836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * InvalidateAllSchemas invalidates all cached schemas
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateAllSchemas() {
    return $Call.ByID(323309817);
}

/**
 * InvalidateSchemaCache invalidates the cached schema for a specific connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function InvalidateSchemaCache(connectionID) {
    return $Call.ByID(3216727651, connectionID);
}

/**
 * ListConnectionDatabases returns the databases available for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<$models.ListDatabasesResponse | null>}
 */
export function ListConnectionDatabases(connectionID) {
    return $Call.ByID(4250284325, connectionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * ListConnections returns all active connections
 * @returns {$CancellablePromise<string[]>}
 */
export function ListConnections() {
    return $Call.ByID(645322174).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * RefreshSchema forces a refresh of the schema for a connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function RefreshSchema(connectionID) {
    return $Call.ByID(2911579779, connectionID);
}

/**
 * RemoveConnection removes a database connection
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveConnection(connectionID) {
    return $Call.ByID(2397696645, connectionID);
}

/**
 * SaveConnection saves connection metadata
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveConnection(req) {
    return $Call.ByID(99910012, req);
}

/**
 * SwitchConnectionDatabase switches the active database for a connection
 * @param {$models.SwitchDatabaseRequest} req
 * @returns {$CancellablePromise<$models.SwitchDatabaseResponse | null>}
 */
export function SwitchConnectionDatabase(req) {
    return $Call.ByID(2707454740, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * TestConnection tests a database connection
 * @param {$models.ConnectionRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(req) {
    return $Call.ByID(854926829, req);
}

// Private type creation functions
const $$createType0 = $models.ConnectionInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.HealthStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = database$0.PoolStats.createFrom;
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Map($Create.Any, $$createType4);
const $$createType9 = $models.ListDatabasesResponse.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = $models.SwitchDatabaseResponse.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
