// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchemaDiffService handles schema comparison operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schemadiff$0 from "./pkg/schemadiff/models.js";

/**
 * CompareConnectionSchemas compares schemas between two database connections
 * @param {string} sourceConnID
 * @param {string} targetConnID
 * @returns {$CancellablePromise<schemadiff$0.SchemaDiff | null>}
 */
export function CompareConnectionSchemas(sourceConnID, targetConnID) {
    return $Call.ByID(3071697380, sourceConnID, targetConnID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CompareWithSnapshot compares a live connection against a saved snapshot
 * @param {string} connectionID
 * @param {string} snapshotID
 * @returns {$CancellablePromise<schemadiff$0.SchemaDiff | null>}
 */
export function CompareWithSnapshot(connectionID, snapshotID) {
    return $Call.ByID(1353733224, connectionID, snapshotID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateSchemaSnapshot creates a point-in-time snapshot of a database schema
 * @param {string} connectionID
 * @param {string} name
 * @returns {$CancellablePromise<schemadiff$0.SnapshotMetadata | null>}
 */
export function CreateSchemaSnapshot(connectionID, name) {
    return $Call.ByID(3122713842, connectionID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeleteSchemaSnapshot deletes a saved snapshot
 * @param {string} snapshotID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSchemaSnapshot(snapshotID) {
    return $Call.ByID(456902973, snapshotID);
}

/**
 * GenerateMigrationSQL generates SQL statements to migrate from source to target schema
 * @param {string} sourceConnID
 * @param {string} targetConnID
 * @param {boolean} reverse
 * @returns {$CancellablePromise<schemadiff$0.MigrationScript | null>}
 */
export function GenerateMigrationSQL(sourceConnID, targetConnID, reverse) {
    return $Call.ByID(3218673422, sourceConnID, targetConnID, reverse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GenerateMigrationSQLFromSnapshot generates SQL to migrate from snapshot to live
 * @param {string} connectionID
 * @param {string} snapshotID
 * @param {boolean} reverse
 * @returns {$CancellablePromise<schemadiff$0.MigrationScript | null>}
 */
export function GenerateMigrationSQLFromSnapshot(connectionID, snapshotID, reverse) {
    return $Call.ByID(2511041734, connectionID, snapshotID, reverse).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSchemaSnapshot retrieves a specific snapshot
 * @param {string} snapshotID
 * @returns {$CancellablePromise<schemadiff$0.SchemaSnapshot | null>}
 */
export function GetSchemaSnapshot(snapshotID) {
    return $Call.ByID(4186385020, snapshotID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ListSchemaSnapshots lists all saved schema snapshots
 * @returns {$CancellablePromise<(schemadiff$0.SnapshotMetadata | null)[]>}
 */
export function ListSchemaSnapshots() {
    return $Call.ByID(2473637479).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = schemadiff$0.SchemaDiff.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = schemadiff$0.SnapshotMetadata.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = schemadiff$0.MigrationScript.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = schemadiff$0.SchemaSnapshot.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType3);
