// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService handles storage, migration, and synthetic view operations for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSyntheticView deletes a synthetic view by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSyntheticView(id) {
    return $Call.ByID(3854916243, id);
}

/**
 * ExecuteSyntheticQuery executes a query against synthetic views
 * @param {string} sql
 * @returns {$CancellablePromise<$models.QueryResponse | null>}
 */
export function ExecuteSyntheticQuery(sql) {
    return $Call.ByID(2835164346, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSyntheticSchema returns the schema information for synthetic views
 * @returns {$CancellablePromise<{ [_ in string]?: any }>}
 */
export function GetSyntheticSchema() {
    return $Call.ByID(2225737572).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSyntheticView retrieves a synthetic view by ID
 * @param {string} id
 * @returns {$CancellablePromise<storage$0.ViewDefinition | null>}
 */
export function GetSyntheticView(id) {
    return $Call.ByID(3497019894, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListSyntheticViews returns a list of all synthetic views
 * @returns {$CancellablePromise<$models.SyntheticViewSummary[]>}
 */
export function ListSyntheticViews() {
    return $Call.ByID(529100323).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SQLiteDeleteConnection removes a connection from SQLite by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteDeleteConnection(id) {
    return $Call.ByID(3302380827, id);
}

/**
 * SQLiteDeleteQuery removes a saved query from SQLite by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteDeleteQuery(id) {
    return $Call.ByID(1652548153, id);
}

/**
 * SQLiteGetConnection returns a single connection by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.SQLiteConnection | null>}
 */
export function SQLiteGetConnection(id) {
    return $Call.ByID(103740828, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * SQLiteGetConnections returns all connections from SQLite
 * @returns {$CancellablePromise<$models.SQLiteConnection[]>}
 */
export function SQLiteGetConnections() {
    return $Call.ByID(2867668797).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SQLiteGetQueries returns all saved queries from SQLite
 * @returns {$CancellablePromise<$models.SQLiteSavedQuery[]>}
 */
export function SQLiteGetQueries() {
    return $Call.ByID(39574780).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * SQLiteGetQuery returns a single query by ID
 * @param {string} id
 * @returns {$CancellablePromise<$models.SQLiteSavedQuery | null>}
 */
export function SQLiteGetQuery(id) {
    return $Call.ByID(3516847336, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * SQLiteGetQueryHistory returns query history from SQLite
 * @param {string} connectionID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SQLiteQueryHistory[]>}
 */
export function SQLiteGetQueryHistory(connectionID, limit) {
    return $Call.ByID(444816272, connectionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * SQLiteGetSetting retrieves a setting from SQLite
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function SQLiteGetSetting(key) {
    return $Call.ByID(1855310904, key);
}

/**
 * SQLiteSaveConnection saves or updates a connection in SQLite
 * Accepts JSON string and parses it into storage.Connection
 * @param {string} connectionJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveConnection(connectionJSON) {
    return $Call.ByID(371378017, connectionJSON);
}

/**
 * SQLiteSaveQuery saves or updates a query in SQLite
 * Accepts JSON string and parses it into storage.SavedQuery
 * @param {string} queryJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveQuery(queryJSON) {
    return $Call.ByID(1433853547, queryJSON);
}

/**
 * SQLiteSaveQueryHistory saves a query history entry to SQLite
 * Accepts JSON string and parses it into storage.QueryHistory
 * @param {string} historyJSON
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSaveQueryHistory(historyJSON) {
    return $Call.ByID(4009481397, historyJSON);
}

/**
 * SQLiteSetSetting saves a setting to SQLite
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SQLiteSetSetting(key, value) {
    return $Call.ByID(3644616044, key, value);
}

/**
 * SaveSyntheticView creates or updates a synthetic view definition
 * @param {storage$0.ViewDefinition} viewDef
 * @returns {$CancellablePromise<string>}
 */
export function SaveSyntheticView(viewDef) {
    return $Call.ByID(357791725, viewDef);
}

/**
 * StorageCompleteMigration marks the IndexedDB to SQLite migration as complete
 * @returns {$CancellablePromise<void>}
 */
export function StorageCompleteMigration() {
    return $Call.ByID(3205473058);
}

/**
 * StorageImportConnections imports connections from IndexedDB format to SQLite
 * @param {string} connectionsJSON
 * @returns {$CancellablePromise<services$0.ImportConnectionsResult | null>}
 */
export function StorageImportConnections(connectionsJSON) {
    return $Call.ByID(2361615749, connectionsJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * StorageImportHistory imports query history from IndexedDB format to SQLite
 * @param {string} historyJSON
 * @returns {$CancellablePromise<services$0.ImportHistoryResult | null>}
 */
export function StorageImportHistory(historyJSON) {
    return $Call.ByID(3310725060, historyJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * StorageImportPreferences imports preferences from IndexedDB format to SQLite
 * @param {string} preferencesJSON
 * @returns {$CancellablePromise<void>}
 */
export function StorageImportPreferences(preferencesJSON) {
    return $Call.ByID(3048605542, preferencesJSON);
}

/**
 * StorageImportQueries imports saved queries from IndexedDB format to SQLite
 * @param {string} queriesJSON
 * @returns {$CancellablePromise<services$0.ImportQueriesResult | null>}
 */
export function StorageImportQueries(queriesJSON) {
    return $Call.ByID(3231970420, queriesJSON).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * StorageMigrationStatus returns the current migration status
 * @returns {$CancellablePromise<services$0.MigrationStatus | null>}
 */
export function StorageMigrationStatus() {
    return $Call.ByID(1942536077).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.QueryResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = storage$0.ViewDefinition.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $models.SyntheticViewSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.SQLiteConnection.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($$createType7);
const $$createType10 = $models.SQLiteSavedQuery.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Nullable($$createType10);
const $$createType13 = $models.SQLiteQueryHistory.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = services$0.ImportConnectionsResult.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
const $$createType17 = services$0.ImportHistoryResult.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = services$0.ImportQueriesResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = services$0.MigrationStatus.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
