// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsFileService handles file operations, dialogs, credentials, and utility functions for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * ClearRecentFiles clears the recent files list
 * @returns {$CancellablePromise<void>}
 */
export function ClearRecentFiles() {
    return $Call.ByID(1164027236);
}

/**
 * CopyFile copies a file from source to destination
 * @param {string} srcPath
 * @param {string} destPath
 * @returns {$CancellablePromise<void>}
 */
export function CopyFile(srcPath, destPath) {
    return $Call.ByID(2793831170, srcPath, destPath);
}

/**
 * CreateDirectory creates a new directory
 * @param {string} dirPath
 * @returns {$CancellablePromise<void>}
 */
export function CreateDirectory(dirPath) {
    return $Call.ByID(3180973136, dirPath);
}

/**
 * CreateTempFile creates a temporary file with the given content
 * @param {string} content
 * @param {string} prefix
 * @param {string} suffix
 * @returns {$CancellablePromise<string>}
 */
export function CreateTempFile(content, prefix, suffix) {
    return $Call.ByID(2949720849, content, prefix, suffix);
}

/**
 * DeleteFile deletes a file
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(filePath) {
    return $Call.ByID(3129988124, filePath);
}

/**
 * DeletePassword deletes a password using the hybrid password manager
 * @param {string} connectionID
 * @returns {$CancellablePromise<void>}
 */
export function DeletePassword(connectionID) {
    return $Call.ByID(2721512247, connectionID);
}

/**
 * FileExists checks if a file exists
 * @param {string} filePath
 * @returns {$CancellablePromise<boolean>}
 */
export function FileExists(filePath) {
    return $Call.ByID(2829512675, filePath);
}

/**
 * GetAppIcon returns the main application icon
 * @returns {$CancellablePromise<string>}
 */
export function GetAppIcon() {
    return $Call.ByID(4071446319).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetAppVersion returns the application version
 * @returns {$CancellablePromise<string>}
 */
export function GetAppVersion() {
    return $Call.ByID(3205691054);
}

/**
 * GetDarkIcon returns the dark theme icon
 * @returns {$CancellablePromise<string>}
 */
export function GetDarkIcon() {
    return $Call.ByID(16467694).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetDownloadsPath returns the user's downloads directory
 * @returns {$CancellablePromise<string>}
 */
export function GetDownloadsPath() {
    return $Call.ByID(1916366023);
}

/**
 * GetFileInfo returns file information
 * @param {string} filePath
 * @returns {$CancellablePromise<services$0.FileInfo | null>}
 */
export function GetFileInfo(filePath) {
    return $Call.ByID(1920610817, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetHomePath returns the user's home directory
 * @returns {$CancellablePromise<string>}
 */
export function GetHomePath() {
    return $Call.ByID(3952801163);
}

/**
 * GetLightIcon returns the light theme icon
 * @returns {$CancellablePromise<string>}
 */
export function GetLightIcon() {
    return $Call.ByID(3262843532).then(/** @type {($result: any) => any} */(($result) => {
        return $Create.ByteSlice($result);
    }));
}

/**
 * GetPassword retrieves a password using the hybrid password manager
 * connectionID is the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, tries keychain fallback
 * @param {string} connectionID
 * @param {string} masterKeyBase64
 * @returns {$CancellablePromise<string>}
 */
export function GetPassword(connectionID, masterKeyBase64) {
    return $Call.ByID(3097389166, connectionID, masterKeyBase64);
}

/**
 * GetRecentFiles returns recently accessed files
 * @returns {$CancellablePromise<services$0.RecentFile[]>}
 */
export function GetRecentFiles() {
    return $Call.ByID(4173751507).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetTempDir returns the system temporary directory
 * @returns {$CancellablePromise<string>}
 */
export function GetTempDir() {
    return $Call.ByID(2739520496);
}

/**
 * GetWorkspaceFiles returns files in a workspace directory
 * @param {string} dirPath
 * @param {string[]} extensions
 * @returns {$CancellablePromise<services$0.FileInfo[]>}
 */
export function GetWorkspaceFiles(dirPath, extensions) {
    return $Call.ByID(2610713531, dirPath, extensions).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * HasPassword checks if a password exists in either keychain or encrypted DB
 * Returns true if the password exists, false otherwise
 * @param {string} connectionID
 * @returns {$CancellablePromise<boolean>}
 */
export function HasPassword(connectionID) {
    return $Call.ByID(2161521058, connectionID);
}

/**
 * OpenEnvFileDialog opens a file dialog for .env files and returns the selected file path and content
 * @returns {$CancellablePromise<{ [_ in string]?: string }>}
 */
export function OpenEnvFileDialog() {
    return $Call.ByID(1112747406).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * OpenFileDialog opens a file dialog and returns the selected file path
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog() {
    return $Call.ByID(1122389771);
}

/**
 * ReadFile reads a file and returns its content
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(filePath) {
    return $Call.ByID(143047699, filePath);
}

/**
 * RemoveFromRecentFiles removes a file from the recent files list
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromRecentFiles(filePath) {
    return $Call.ByID(3207503817, filePath);
}

/**
 * SaveFileDialog opens a save file dialog and returns the selected file path
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog() {
    return $Call.ByID(1467727518);
}

/**
 * SaveToDownloads saves content to a file in the downloads directory
 * @param {string} filename
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveToDownloads(filename, content) {
    return $Call.ByID(2910675050, filename, content);
}

/**
 * ShowErrorDialog shows an error dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowErrorDialog(title, message) {
    return $Call.ByID(1256079434, title, message);
}

/**
 * ShowInfoDialog shows an information dialog
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function ShowInfoDialog(title, message) {
    return $Call.ByID(3682785280, title, message);
}

/**
 * ShowNotification shows a notification dialog
 * @param {string} title
 * @param {string} message
 * @param {boolean} isError
 * @returns {$CancellablePromise<void>}
 */
export function ShowNotification(title, message, isError) {
    return $Call.ByID(2013254451, title, message, isError);
}

/**
 * ShowQuestionDialog shows a question dialog and returns the result
 * @param {string} title
 * @param {string} message
 * @returns {$CancellablePromise<boolean>}
 */
export function ShowQuestionDialog(title, message) {
    return $Call.ByID(1517545248, title, message);
}

/**
 * StorePassword stores a password securely using the hybrid password manager
 * connectionID is used as the identifier for the stored credential
 * masterKeyBase64 is an optional base64-encoded master key from the authenticated session
 * If empty, uses keychain only (graceful degradation)
 * @param {string} connectionID
 * @param {string} password
 * @param {string} masterKeyBase64
 * @returns {$CancellablePromise<void>}
 */
export function StorePassword(connectionID, password, masterKeyBase64) {
    return $Call.ByID(2636618051, connectionID, password, masterKeyBase64);
}

/**
 * WriteFile writes content to a file
 * @param {string} filePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteFile(filePath, content) {
    return $Call.ByID(3312018874, filePath, content);
}

// Private type creation functions
const $$createType0 = services$0.FileInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = services$0.RecentFile.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
