// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsAlertService exposes standalone time-series alert CRUD to the frontend
 * and runs the background monitor that fires them. It wraps the Wails-free
 * internal/alertsvc orchestration and internal/alertsched monitor, supplying a
 * SeriesFetcher over the database service and a Dispatcher over the event
 * emitter.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckAlertNow evaluates an alert immediately (without affecting the monitor's
 * firing state), so the UI can preview whether a rule currently fires.
 * @param {string} id
 * @returns {$CancellablePromise<$models.AlertCheckResponse | null>}
 */
export function CheckAlertNow(id) {
    return $Call.ByID(2059536885, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteAlert removes an alert.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAlert(id) {
    return $Call.ByID(397464184, id);
}

/**
 * GetAlert loads an alert by ID.
 * @param {string} id
 * @returns {$CancellablePromise<storage$0.TimeSeriesAlert | null>}
 */
export function GetAlert(id) {
    return $Call.ByID(2054249547, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListAlerts returns all stored alerts.
 * @returns {$CancellablePromise<storage$0.TimeSeriesAlert[]>}
 */
export function ListAlerts() {
    return $Call.ByID(3565398114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SaveAlert validates and persists an alert, returning its ID.
 * @param {$models.AlertRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function SaveAlert(req) {
    return $Call.ByID(2535353862, req);
}

/**
 * SetAlertEnabled toggles an alert on or off.
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAlertEnabled(id, enabled) {
    return $Call.ByID(619027036, id, enabled);
}

/**
 * SetStore injects the alert store once storage is ready.
 * @param {storage$0.TimeSeriesAlertStore | null} store
 * @returns {$CancellablePromise<void>}
 */
export function SetStore(store) {
    return $Call.ByID(621167356, store);
}

/**
 * Start launches the background monitor loop. It is safe to call once after the
 * store is set; subsequent calls are no-ops while running.
 * @returns {$CancellablePromise<void>}
 */
export function Start() {
    return $Call.ByID(2050135263);
}

/**
 * Stop halts the monitor loop (called on shutdown).
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(1227315941);
}

// Private type creation functions
const $$createType0 = $models.AlertCheckResponse.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.TimeSeriesAlert.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType2);
