// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsReportService is a Wails-compatible service that wraps services.ReportService
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * DeleteReport removes a report definition
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteReport(id) {
    return $Call.ByID(864806236, id);
}

/**
 * GetReport loads a full report definition by ID
 * @param {string} id
 * @returns {$CancellablePromise<storage$0.Report | null>}
 */
export function GetReport(id) {
    return $Call.ByID(561119925, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListReports returns summaries for all saved reports
 * @returns {$CancellablePromise<storage$0.ReportSummary[]>}
 */
export function ListReports() {
    return $Call.ByID(1848559576).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RunReport executes all (or selected) components within a report
 * @param {services$0.ReportRunRequest} req
 * @returns {$CancellablePromise<services$0.ReportRunResponse | null>}
 */
export function RunReport(req) {
    return $Call.ByID(1031713844, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SaveReport creates or updates a report definition
 * @param {storage$0.Report} report
 * @returns {$CancellablePromise<storage$0.Report | null>}
 */
export function SaveReport(report) {
    return $Call.ByID(24920302, report).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = storage$0.Report.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.ReportSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = services$0.ReportRunResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
