// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsKeyboardService handles keyboard-related operations for Wails v3
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "./services/models.js";

/**
 * AddKeyboardBinding adds a new keyboard binding
 * @param {string} key
 * @param {services$0.KeyboardAction} action
 * @returns {$CancellablePromise<void>}
 */
export function AddKeyboardBinding(key, action) {
    return $Call.ByID(2587193697, key, action);
}

/**
 * ExportKeyboardBindings exports all keyboard bindings
 * @returns {$CancellablePromise<{ [_ in string]?: services$0.KeyboardAction }>}
 */
export function ExportKeyboardBindings() {
    return $Call.ByID(244471435).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAllKeyboardBindings returns all keyboard bindings
 * @returns {$CancellablePromise<{ [_ in string]?: services$0.KeyboardAction }>}
 */
export function GetAllKeyboardBindings() {
    return $Call.ByID(122030866).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetKeyboardBindingsByCategory returns keyboard bindings grouped by category
 * @returns {$CancellablePromise<{ [_ in string]?: services$0.KeyboardAction[] }>}
 */
export function GetKeyboardBindingsByCategory() {
    return $Call.ByID(1363231388).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * HandleKeyboardEvent handles keyboard events
 * @param {services$0.KeyboardEvent} event
 * @returns {$CancellablePromise<void>}
 */
export function HandleKeyboardEvent(event) {
    return $Call.ByID(3917158859, event);
}

/**
 * ImportKeyboardBindings imports keyboard bindings
 * @param {{ [_ in string]?: services$0.KeyboardAction }} bindings
 * @returns {$CancellablePromise<void>}
 */
export function ImportKeyboardBindings(bindings) {
    return $Call.ByID(1545682240, bindings);
}

/**
 * RemoveKeyboardBinding removes a keyboard binding
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function RemoveKeyboardBinding(key) {
    return $Call.ByID(1740944284, key);
}

/**
 * ResetKeyboardBindings resets keyboard bindings to defaults
 * @returns {$CancellablePromise<void>}
 */
export function ResetKeyboardBindings() {
    return $Call.ByID(2781976602);
}

// Private type creation functions
const $$createType0 = services$0.KeyboardAction.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $Create.Map($Create.Any, $$createType2);
