// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WailsNotebookService exposes notebook CRUD and execution to the frontend. It
 * wraps the Wails-free internal/notebooksvc orchestration: read SQL cells run
 * read-only, action cells run as writes (gated by the dry-run/approval guard),
 * notify cells emit events, and cross-cell composition runs on the DuckDB
 * compute engine when available.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notebooksvc$0 from "./internal/notebooksvc/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "./pkg/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteNotebook removes a notebook and its history.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNotebook(id) {
    return $Call.ByID(3627656324, id);
}

/**
 * GetNotebook loads a notebook definition by ID.
 * @param {string} id
 * @returns {$CancellablePromise<notebooksvc$0.DefinitionDTO | null>}
 */
export function GetNotebook(id) {
    return $Call.ByID(3676261483, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListNotebooks returns notebook summaries.
 * @returns {$CancellablePromise<storage$0.NotebookSummary[]>}
 */
export function ListNotebooks() {
    return $Call.ByID(358314536).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * NotebookHistory returns recent runs for a notebook.
 * @param {string} id
 * @param {number} limit
 * @returns {$CancellablePromise<storage$0.NotebookRun[]>}
 */
export function NotebookHistory(id, limit) {
    return $Call.ByID(3453679553, id, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RunNotebook executes a stored notebook and returns the per-cell outputs.
 * @param {$models.RunNotebookRequest} req
 * @returns {$CancellablePromise<notebooksvc$0.RunResultDTO | null>}
 */
export function RunNotebook(req) {
    return $Call.ByID(153813634, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SaveNotebook validates and persists a notebook definition, returning its ID.
 * @param {notebooksvc$0.DefinitionDTO} def
 * @returns {$CancellablePromise<string>}
 */
export function SaveNotebook(def) {
    return $Call.ByID(3826997014, def);
}

/**
 * SetStore injects the notebook store once storage is ready.
 * @param {storage$0.NotebookStore | null} store
 * @returns {$CancellablePromise<void>}
 */
export function SetStore(store) {
    return $Call.ByID(2231842663, store);
}

// Private type creation functions
const $$createType0 = notebooksvc$0.DefinitionDTO.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = storage$0.NotebookSummary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = storage$0.NotebookRun.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = notebooksvc$0.RunResultDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
