// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ColumnDiff represents the diff for a single column
 */
export class ColumnDiff {
    /**
     * Creates a new ColumnDiff instance.
     * @param {Partial<ColumnDiff>} [$$source = {}] - The source object to create the ColumnDiff.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["old_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["new_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["old_nullable"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["new_nullable"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["old_default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["new_default"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnDiff}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDiff(/** @type {Partial<ColumnDiff>} */($$parsedSource));
    }
}

/**
 * DiffStatus represents the status of a schema object in a diff
 * @readonly
 * @enum {string}
 */
export const DiffStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DiffAdded: "added",
    DiffRemoved: "removed",
    DiffModified: "modified",
    DiffUnchanged: "unchanged",
};

/**
 * DiffSummary provides aggregate statistics about the diff
 */
export class DiffSummary {
    /**
     * Creates a new DiffSummary instance.
     * @param {Partial<DiffSummary>} [$$source = {}] - The source object to create the DiffSummary.
     */
    constructor($$source = {}) {
        if (!("tables_added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tables_added"] = 0;
        }
        if (!("tables_removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tables_removed"] = 0;
        }
        if (!("tables_modified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tables_modified"] = 0;
        }
        if (!("columns_added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["columns_added"] = 0;
        }
        if (!("columns_removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["columns_removed"] = 0;
        }
        if (!("columns_modified" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["columns_modified"] = 0;
        }
        if (!("indexes_changed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexes_changed"] = 0;
        }
        if (!("fks_changed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fks_changed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffSummary(/** @type {Partial<DiffSummary>} */($$parsedSource));
    }
}

/**
 * FKDiff represents the diff for a single foreign key
 */
export class FKDiff {
    /**
     * Creates a new FKDiff instance.
     * @param {Partial<FKDiff>} [$$source = {}] - The source object to create the FKDiff.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["old_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["new_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["old_ref_table"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["new_ref_table"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["old_ref_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["new_ref_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["old_on_delete"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["new_on_delete"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["old_on_update"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["new_on_update"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FKDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FKDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("old_columns" in $$parsedSource) {
            $$parsedSource["old_columns"] = $$createField2_0($$parsedSource["old_columns"]);
        }
        if ("new_columns" in $$parsedSource) {
            $$parsedSource["new_columns"] = $$createField3_0($$parsedSource["new_columns"]);
        }
        if ("old_ref_columns" in $$parsedSource) {
            $$parsedSource["old_ref_columns"] = $$createField6_0($$parsedSource["old_ref_columns"]);
        }
        if ("new_ref_columns" in $$parsedSource) {
            $$parsedSource["new_ref_columns"] = $$createField7_0($$parsedSource["new_ref_columns"]);
        }
        return new FKDiff(/** @type {Partial<FKDiff>} */($$parsedSource));
    }
}

/**
 * IndexDiff represents the diff for a single index
 */
export class IndexDiff {
    /**
     * Creates a new IndexDiff instance.
     * @param {Partial<IndexDiff>} [$$source = {}] - The source object to create the IndexDiff.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["old_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["new_columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["old_unique"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["new_unique"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["old_method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["new_method"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("old_columns" in $$parsedSource) {
            $$parsedSource["old_columns"] = $$createField2_0($$parsedSource["old_columns"]);
        }
        if ("new_columns" in $$parsedSource) {
            $$parsedSource["new_columns"] = $$createField3_0($$parsedSource["new_columns"]);
        }
        return new IndexDiff(/** @type {Partial<IndexDiff>} */($$parsedSource));
    }
}

/**
 * MigrationDirection specifies the direction of migration
 * @readonly
 * @enum {string}
 */
export const MigrationDirection = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Source -> Target
     */
    MigrationForward: "forward",

    /**
     * Target -> Source
     */
    MigrationBackward: "backward",
};

/**
 * MigrationScript represents a generated migration script
 */
export class MigrationScript {
    /**
     * Creates a new MigrationScript instance.
     * @param {Partial<MigrationScript>} [$$source = {}] - The source object to create the MigrationScript.
     */
    constructor($$source = {}) {
        if (!("direction" in $$source)) {
            /**
             * @member
             * @type {MigrationDirection}
             */
            this["direction"] = MigrationDirection.$zero;
        }
        if (!("database_type" in $$source)) {
            /**
             * @member
             * @type {database$0.DatabaseType}
             */
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("generated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["generated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("target_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrationScript instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrationScript}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrationScript(/** @type {Partial<MigrationScript>} */($$parsedSource));
    }
}

/**
 * SchemaDiff represents the complete diff between two database schemas
 */
export class SchemaDiff {
    /**
     * Creates a new SchemaDiff instance.
     * @param {Partial<SchemaDiff>} [$$source = {}] - The source object to create the SchemaDiff.
     */
    constructor($$source = {}) {
        if (!("source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("target_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target_id"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {DiffSummary}
             */
            this["summary"] = (new DiffSummary());
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {TableDiff[]}
             */
            this["tables"] = [];
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["duration"] = time$0.Duration.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchemaDiff}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField3_0($$parsedSource["summary"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField4_0($$parsedSource["tables"]);
        }
        return new SchemaDiff(/** @type {Partial<SchemaDiff>} */($$parsedSource));
    }
}

/**
 * SchemaSnapshot represents a saved point-in-time snapshot of a database schema
 */
export class SchemaSnapshot {
    /**
     * Creates a new SchemaSnapshot instance.
     * @param {Partial<SchemaSnapshot>} [$$source = {}] - The source object to create the SchemaSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("database_type" in $$source)) {
            /**
             * @member
             * @type {database$0.DatabaseType}
             */
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("schemas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["schemas"] = [];
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: database$0.TableInfo[] }}
             */
            this["tables"] = {};
        }
        if (!("structures" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: database$0.TableStructure | null }}
             */
            this["structures"] = {};
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchemaSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schemas" in $$parsedSource) {
            $$parsedSource["schemas"] = $$createField4_0($$parsedSource["schemas"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField5_0($$parsedSource["tables"]);
        }
        if ("structures" in $$parsedSource) {
            $$parsedSource["structures"] = $$createField6_0($$parsedSource["structures"]);
        }
        return new SchemaSnapshot(/** @type {Partial<SchemaSnapshot>} */($$parsedSource));
    }
}

/**
 * SnapshotMetadata provides lightweight snapshot info for listing
 */
export class SnapshotMetadata {
    /**
     * Creates a new SnapshotMetadata instance.
     * @param {Partial<SnapshotMetadata>} [$$source = {}] - The source object to create the SnapshotMetadata.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("database_type" in $$source)) {
            /**
             * @member
             * @type {database$0.DatabaseType}
             */
            this["database_type"] = database$0.DatabaseType.$zero;
        }
        if (!("table_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["table_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("size_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_bytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SnapshotMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SnapshotMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SnapshotMetadata(/** @type {Partial<SnapshotMetadata>} */($$parsedSource));
    }
}

/**
 * TableDiff represents the diff for a single table
 */
export class TableDiff {
    /**
     * Creates a new TableDiff instance.
     * @param {Partial<TableDiff>} [$$source = {}] - The source object to create the TableDiff.
     */
    constructor($$source = {}) {
        if (!("schema" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {DiffStatus}
             */
            this["status"] = DiffStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ColumnDiff[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {IndexDiff[] | undefined}
             */
            this["indexes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FKDiff[] | undefined}
             */
            this["foreign_keys"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableDiff}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType11;
        const $$createField4_0 = $$createType13;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField3_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField4_0($$parsedSource["indexes"]);
        }
        if ("foreign_keys" in $$parsedSource) {
            $$parsedSource["foreign_keys"] = $$createField5_0($$parsedSource["foreign_keys"]);
        }
        return new TableDiff(/** @type {Partial<TableDiff>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = DiffSummary.createFrom;
const $$createType2 = TableDiff.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = database$0.TableInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Map($Create.Any, $$createType5);
const $$createType7 = database$0.TableStructure.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Map($Create.Any, $$createType8);
const $$createType10 = ColumnDiff.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = IndexDiff.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = FKDiff.createFrom;
const $$createType15 = $Create.Array($$createType14);
