# Prometheus configuration for HowlerOps monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  # - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # HowlerOps Backend metrics
  - job_name: 'sql-studio-backend'
    static_configs:
      - targets: ['sql-studio-backend:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # Node.js process metrics from backend
  - job_name: 'sql-studio-backend-process'
    static_configs:
      - targets: ['sql-studio-backend:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics

  # Nginx metrics from frontend
  - job_name: 'sql-studio-frontend'
    static_configs:
      - targets: ['sql-studio-frontend:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    honor_labels: true

  # PostgreSQL metrics (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    honor_labels: true

  # Redis metrics (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    honor_labels: true

  # Docker container metrics (requires cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    honor_labels: true

  # Node exporter for system metrics (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    honor_labels: true

# Recording rules for performance optimization
# rule_files:
#   - "recording_rules.yml"

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB