// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CellDTO is a single notebook cell.
 */
export class CellDTO {
    /**
     * Creates a new CellDTO instance.
     * @param {Partial<CellDTO>} [$$source = {}] - The source object to create the CellDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * stable handle for references
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dependsOn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["connectionId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sql"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["markdown"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["channel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ChartSpecDTO | null | undefined}
             */
            this["chart"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CellDTO}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dependsOn" in $$parsedSource) {
            $$parsedSource["dependsOn"] = $$createField4_0($$parsedSource["dependsOn"]);
        }
        if ("chart" in $$parsedSource) {
            $$parsedSource["chart"] = $$createField10_0($$parsedSource["chart"]);
        }
        return new CellDTO(/** @type {Partial<CellDTO>} */($$parsedSource));
    }
}

/**
 * CellResultDTO is the wire form of a cell's output.
 */
export class CellResultDTO {
    /**
     * Creates a new CellResultDTO instance.
     * @param {Partial<CellResultDTO>} [$$source = {}] - The source object to create the CellResultDTO.
     */
    constructor($$source = {}) {
        if (!("cellId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cellId"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["markdown"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sql"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }[] | undefined}
             */
            this["rows"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["rowCount"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["affected"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["notified"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["planned"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ChartSpecDTO | null | undefined}
             */
            this["chart"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skipped"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CellResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CellResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType4;
        const $$createField14_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField8_0($$parsedSource["rows"]);
        }
        if ("chart" in $$parsedSource) {
            $$parsedSource["chart"] = $$createField14_0($$parsedSource["chart"]);
        }
        return new CellResultDTO(/** @type {Partial<CellResultDTO>} */($$parsedSource));
    }
}

/**
 * ChartSpecDTO describes a chart cell's visualization.
 */
export class ChartSpecDTO {
    /**
     * Creates a new ChartSpecDTO instance.
     * @param {Partial<ChartSpecDTO>} [$$source = {}] - The source object to create the ChartSpecDTO.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["x"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["y"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["stacked"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartSpecDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChartSpecDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("y" in $$parsedSource) {
            $$parsedSource["y"] = $$createField3_0($$parsedSource["y"]);
        }
        return new ChartSpecDTO(/** @type {Partial<ChartSpecDTO>} */($$parsedSource));
    }
}

/**
 * DefinitionDTO is the wire form of a notebook definition.
 */
export class DefinitionDTO {
    /**
     * Creates a new DefinitionDTO instance.
     * @param {Partial<DefinitionDTO>} [$$source = {}] - The source object to create the DefinitionDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["id"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {InputDTO[] | undefined}
             */
            this["inputs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CellDTO[] | undefined}
             */
            this["cells"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DefinitionDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DefinitionDTO}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField3_0($$parsedSource["inputs"]);
        }
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField4_0($$parsedSource["cells"]);
        }
        return new DefinitionDTO(/** @type {Partial<DefinitionDTO>} */($$parsedSource));
    }
}

/**
 * InputDTO is a typed notebook input (widget) definition.
 */
export class InputDTO {
    /**
     * Creates a new InputDTO instance.
     * @param {Partial<InputDTO>} [$$source = {}] - The source object to create the InputDTO.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["required"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pattern"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["min"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["max"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ElementType types the elements of a list input (e.g. "integer" so an IN
             * clause renders bare numbers, not quoted strings). Empty defaults to string.
             * @member
             * @type {string | undefined}
             */
            this["elementType"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InputDTO}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new InputDTO(/** @type {Partial<InputDTO>} */($$parsedSource));
    }
}

/**
 * RunResultDTO is the wire form of a notebook run.
 */
export class RunResultDTO {
    /**
     * Creates a new RunResultDTO instance.
     * @param {Partial<RunResultDTO>} [$$source = {}] - The source object to create the RunResultDTO.
     */
    constructor($$source = {}) {
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["failed"] = false;
        }
        if (!("dryRun" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dryRun"] = false;
        }
        if (!("cells" in $$source)) {
            /**
             * @member
             * @type {CellResultDTO[]}
             */
            this["cells"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RunResultDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RunResultDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cells" in $$parsedSource) {
            $$parsedSource["cells"] = $$createField2_0($$parsedSource["cells"]);
        }
        return new RunResultDTO(/** @type {Partial<RunResultDTO>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ChartSpecDTO.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = InputDTO.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CellDTO.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = CellResultDTO.createFrom;
const $$createType10 = $Create.Array($$createType9);
