// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: query.proto

package query

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query types
type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED QueryType = 0
	QueryType_QUERY_TYPE_SELECT      QueryType = 1
	QueryType_QUERY_TYPE_INSERT      QueryType = 2
	QueryType_QUERY_TYPE_UPDATE      QueryType = 3
	QueryType_QUERY_TYPE_DELETE      QueryType = 4
	QueryType_QUERY_TYPE_DDL         QueryType = 5
	QueryType_QUERY_TYPE_TRANSACTION QueryType = 6
	QueryType_QUERY_TYPE_EXPLAIN     QueryType = 7
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_SELECT",
		2: "QUERY_TYPE_INSERT",
		3: "QUERY_TYPE_UPDATE",
		4: "QUERY_TYPE_DELETE",
		5: "QUERY_TYPE_DDL",
		6: "QUERY_TYPE_TRANSACTION",
		7: "QUERY_TYPE_EXPLAIN",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED": 0,
		"QUERY_TYPE_SELECT":      1,
		"QUERY_TYPE_INSERT":      2,
		"QUERY_TYPE_UPDATE":      3,
		"QUERY_TYPE_DELETE":      4,
		"QUERY_TYPE_DDL":         5,
		"QUERY_TYPE_TRANSACTION": 6,
		"QUERY_TYPE_EXPLAIN":     7,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[0].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[0]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

// Query execution mode
type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_EXECUTION_MODE_IMMEDIATE   ExecutionMode = 1
	ExecutionMode_EXECUTION_MODE_STREAMING   ExecutionMode = 2
	ExecutionMode_EXECUTION_MODE_BATCH       ExecutionMode = 3
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "EXECUTION_MODE_IMMEDIATE",
		2: "EXECUTION_MODE_STREAMING",
		3: "EXECUTION_MODE_BATCH",
	}
	ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"EXECUTION_MODE_IMMEDIATE":   1,
		"EXECUTION_MODE_STREAMING":   2,
		"EXECUTION_MODE_BATCH":       3,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[1].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[1]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

// Data format for streaming
type DataFormat int32

const (
	DataFormat_DATA_FORMAT_UNSPECIFIED DataFormat = 0
	DataFormat_DATA_FORMAT_JSON        DataFormat = 1
	DataFormat_DATA_FORMAT_NDJSON      DataFormat = 2
	DataFormat_DATA_FORMAT_CSV         DataFormat = 3
	DataFormat_DATA_FORMAT_PROTOBUF    DataFormat = 4
)

// Enum value maps for DataFormat.
var (
	DataFormat_name = map[int32]string{
		0: "DATA_FORMAT_UNSPECIFIED",
		1: "DATA_FORMAT_JSON",
		2: "DATA_FORMAT_NDJSON",
		3: "DATA_FORMAT_CSV",
		4: "DATA_FORMAT_PROTOBUF",
	}
	DataFormat_value = map[string]int32{
		"DATA_FORMAT_UNSPECIFIED": 0,
		"DATA_FORMAT_JSON":        1,
		"DATA_FORMAT_NDJSON":      2,
		"DATA_FORMAT_CSV":         3,
		"DATA_FORMAT_PROTOBUF":    4,
	}
)

func (x DataFormat) Enum() *DataFormat {
	p := new(DataFormat)
	*p = x
	return p
}

func (x DataFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[2].Descriptor()
}

func (DataFormat) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[2]
}

func (x DataFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataFormat.Descriptor instead.
func (DataFormat) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

// Streaming query response types
type StreamResponseType int32

const (
	StreamResponseType_STREAM_RESPONSE_TYPE_UNSPECIFIED StreamResponseType = 0
	StreamResponseType_STREAM_RESPONSE_TYPE_METADATA    StreamResponseType = 1
	StreamResponseType_STREAM_RESPONSE_TYPE_DATA        StreamResponseType = 2
	StreamResponseType_STREAM_RESPONSE_TYPE_PROGRESS    StreamResponseType = 3
	StreamResponseType_STREAM_RESPONSE_TYPE_COMPLETE    StreamResponseType = 4
	StreamResponseType_STREAM_RESPONSE_TYPE_ERROR       StreamResponseType = 5
)

// Enum value maps for StreamResponseType.
var (
	StreamResponseType_name = map[int32]string{
		0: "STREAM_RESPONSE_TYPE_UNSPECIFIED",
		1: "STREAM_RESPONSE_TYPE_METADATA",
		2: "STREAM_RESPONSE_TYPE_DATA",
		3: "STREAM_RESPONSE_TYPE_PROGRESS",
		4: "STREAM_RESPONSE_TYPE_COMPLETE",
		5: "STREAM_RESPONSE_TYPE_ERROR",
	}
	StreamResponseType_value = map[string]int32{
		"STREAM_RESPONSE_TYPE_UNSPECIFIED": 0,
		"STREAM_RESPONSE_TYPE_METADATA":    1,
		"STREAM_RESPONSE_TYPE_DATA":        2,
		"STREAM_RESPONSE_TYPE_PROGRESS":    3,
		"STREAM_RESPONSE_TYPE_COMPLETE":    4,
		"STREAM_RESPONSE_TYPE_ERROR":       5,
	}
)

func (x StreamResponseType) Enum() *StreamResponseType {
	p := new(StreamResponseType)
	*p = x
	return p
}

func (x StreamResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[3].Descriptor()
}

func (StreamResponseType) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[3]
}

func (x StreamResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamResponseType.Descriptor instead.
func (StreamResponseType) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

// Query status
type QueryStatus int32

const (
	QueryStatus_QUERY_STATUS_UNSPECIFIED QueryStatus = 0
	QueryStatus_QUERY_STATUS_PENDING     QueryStatus = 1
	QueryStatus_QUERY_STATUS_RUNNING     QueryStatus = 2
	QueryStatus_QUERY_STATUS_COMPLETED   QueryStatus = 3
	QueryStatus_QUERY_STATUS_FAILED      QueryStatus = 4
	QueryStatus_QUERY_STATUS_CANCELLED   QueryStatus = 5
)

// Enum value maps for QueryStatus.
var (
	QueryStatus_name = map[int32]string{
		0: "QUERY_STATUS_UNSPECIFIED",
		1: "QUERY_STATUS_PENDING",
		2: "QUERY_STATUS_RUNNING",
		3: "QUERY_STATUS_COMPLETED",
		4: "QUERY_STATUS_FAILED",
		5: "QUERY_STATUS_CANCELLED",
	}
	QueryStatus_value = map[string]int32{
		"QUERY_STATUS_UNSPECIFIED": 0,
		"QUERY_STATUS_PENDING":     1,
		"QUERY_STATUS_RUNNING":     2,
		"QUERY_STATUS_COMPLETED":   3,
		"QUERY_STATUS_FAILED":      4,
		"QUERY_STATUS_CANCELLED":   5,
	}
)

func (x QueryStatus) Enum() *QueryStatus {
	p := new(QueryStatus)
	*p = x
	return p
}

func (x QueryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[4].Descriptor()
}

func (QueryStatus) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[4]
}

func (x QueryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryStatus.Descriptor instead.
func (QueryStatus) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

type BatchEditOperation_OperationType int32

const (
	BatchEditOperation_OPERATION_TYPE_UNSPECIFIED BatchEditOperation_OperationType = 0
	BatchEditOperation_OPERATION_TYPE_INSERT      BatchEditOperation_OperationType = 1
	BatchEditOperation_OPERATION_TYPE_UPDATE      BatchEditOperation_OperationType = 2
	BatchEditOperation_OPERATION_TYPE_DELETE      BatchEditOperation_OperationType = 3
)

// Enum value maps for BatchEditOperation_OperationType.
var (
	BatchEditOperation_OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_UNSPECIFIED",
		1: "OPERATION_TYPE_INSERT",
		2: "OPERATION_TYPE_UPDATE",
		3: "OPERATION_TYPE_DELETE",
	}
	BatchEditOperation_OperationType_value = map[string]int32{
		"OPERATION_TYPE_UNSPECIFIED": 0,
		"OPERATION_TYPE_INSERT":      1,
		"OPERATION_TYPE_UPDATE":      2,
		"OPERATION_TYPE_DELETE":      3,
	}
)

func (x BatchEditOperation_OperationType) Enum() *BatchEditOperation_OperationType {
	p := new(BatchEditOperation_OperationType)
	*p = x
	return p
}

func (x BatchEditOperation_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchEditOperation_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_query_proto_enumTypes[5].Descriptor()
}

func (BatchEditOperation_OperationType) Type() protoreflect.EnumType {
	return &file_query_proto_enumTypes[5]
}

func (x BatchEditOperation_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchEditOperation_OperationType.Descriptor instead.
func (BatchEditOperation_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{18, 0}
}

// Execute query request
type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    map[string]*anypb.Any  `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options       *QueryOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	QueryId       string                 `protobuf:"bytes,5,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"` // Optional client-provided ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteQueryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ExecuteQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteQueryRequest) GetParameters() map[string]*anypb.Any {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteQueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ExecuteQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

// Query options
type QueryOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Limit           int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	TimeoutSeconds  int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ReadOnly        bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	Explain         bool                   `protobuf:"varint,4,opt,name=explain,proto3" json:"explain,omitempty"`
	Format          DataFormat             `protobuf:"varint,5,opt,name=format,proto3,enum=sqlstudio.query.DataFormat" json:"format,omitempty"`
	IncludeMetadata bool                   `protobuf:"varint,6,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	FetchSize       int32                  `protobuf:"varint,7,opt,name=fetch_size,json=fetchSize,proto3" json:"fetch_size,omitempty"` // For streaming
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryOptions) Reset() {
	*x = QueryOptions{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOptions) ProtoMessage() {}

func (x *QueryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOptions.ProtoReflect.Descriptor instead.
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryOptions) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryOptions) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *QueryOptions) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

func (x *QueryOptions) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *QueryOptions) GetFormat() DataFormat {
	if x != nil {
		return x.Format
	}
	return DataFormat_DATA_FORMAT_UNSPECIFIED
}

func (x *QueryOptions) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

func (x *QueryOptions) GetFetchSize() int32 {
	if x != nil {
		return x.FetchSize
	}
	return 0
}

// Column metadata
type ColumnMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Ordinal       int32                  `protobuf:"varint,4,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	TableName     string                 `protobuf:"bytes,5,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SchemaName    string                 `protobuf:"bytes,6,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMetadata) Reset() {
	*x = ColumnMetadata{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMetadata) ProtoMessage() {}

func (x *ColumnMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMetadata.ProtoReflect.Descriptor instead.
func (*ColumnMetadata) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColumnMetadata) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ColumnMetadata) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *ColumnMetadata) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ColumnMetadata) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ColumnMetadata) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

// Query result row
type QueryRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*anypb.Any           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRow) Reset() {
	*x = QueryRow{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRow) ProtoMessage() {}

func (x *QueryRow) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRow.ProtoReflect.Descriptor instead.
func (*QueryRow) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRow) GetValues() []*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

// Query results
type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnMetadata      `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*QueryRow            `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	RowCount      int64                  `protobuf:"varint,3,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	MoreResults   bool                   `protobuf:"varint,4,opt,name=more_results,json=moreResults,proto3" json:"more_results,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"` // For pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResult) GetColumns() []*ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResult) GetRows() []*QueryRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResult) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *QueryResult) GetMoreResults() bool {
	if x != nil {
		return x.MoreResults
	}
	return false
}

func (x *QueryResult) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Query execution statistics
type QueryStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartTime       *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	DurationMs      int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RowsAffected    int64                  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	RowsReturned    int64                  `protobuf:"varint,5,opt,name=rows_returned,json=rowsReturned,proto3" json:"rows_returned,omitempty"`
	BytesProcessed  int64                  `protobuf:"varint,6,opt,name=bytes_processed,json=bytesProcessed,proto3" json:"bytes_processed,omitempty"`
	BytesReturned   int64                  `protobuf:"varint,7,opt,name=bytes_returned,json=bytesReturned,proto3" json:"bytes_returned,omitempty"`
	CpuTimeMs       float64                `protobuf:"fixed64,8,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	MemoryUsedBytes int64                  `protobuf:"varint,9,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	DiskReads       int64                  `protobuf:"varint,10,opt,name=disk_reads,json=diskReads,proto3" json:"disk_reads,omitempty"`
	DiskWrites      int64                  `protobuf:"varint,11,opt,name=disk_writes,json=diskWrites,proto3" json:"disk_writes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryStats) Reset() {
	*x = QueryStats{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStats) ProtoMessage() {}

func (x *QueryStats) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStats.ProtoReflect.Descriptor instead.
func (*QueryStats) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStats) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *QueryStats) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *QueryStats) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *QueryStats) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryStats) GetRowsReturned() int64 {
	if x != nil {
		return x.RowsReturned
	}
	return 0
}

func (x *QueryStats) GetBytesProcessed() int64 {
	if x != nil {
		return x.BytesProcessed
	}
	return 0
}

func (x *QueryStats) GetBytesReturned() int64 {
	if x != nil {
		return x.BytesReturned
	}
	return 0
}

func (x *QueryStats) GetCpuTimeMs() float64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *QueryStats) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *QueryStats) GetDiskReads() int64 {
	if x != nil {
		return x.DiskReads
	}
	return 0
}

func (x *QueryStats) GetDiskWrites() int64 {
	if x != nil {
		return x.DiskWrites
	}
	return 0
}

// Execute query response
type ExecuteQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	QueryId       string                 `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Result        *QueryResult           `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	Warnings      []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteQueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *ExecuteQueryResponse) GetResult() *QueryResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteQueryResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ExecuteQueryResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Execute streaming query request
type ExecuteStreamingQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    map[string]*anypb.Any  `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options       *QueryOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	QueryId       string                 `protobuf:"bytes,5,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStreamingQueryRequest) Reset() {
	*x = ExecuteStreamingQueryRequest{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStreamingQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStreamingQueryRequest) ProtoMessage() {}

func (x *ExecuteStreamingQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStreamingQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStreamingQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteStreamingQueryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ExecuteStreamingQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExecuteStreamingQueryRequest) GetParameters() map[string]*anypb.Any {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteStreamingQueryRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ExecuteStreamingQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

// Query progress information
type QueryProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RowsProcessed      int64                  `protobuf:"varint,1,opt,name=rows_processed,json=rowsProcessed,proto3" json:"rows_processed,omitempty"`
	TotalRows          int64                  `protobuf:"varint,2,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"` // If known
	ProgressPercentage float64                `protobuf:"fixed64,3,opt,name=progress_percentage,json=progressPercentage,proto3" json:"progress_percentage,omitempty"`
	LastUpdate         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	CurrentPhase       string                 `protobuf:"bytes,5,opt,name=current_phase,json=currentPhase,proto3" json:"current_phase,omitempty"`
	Metrics            map[string]string      `protobuf:"bytes,6,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryProgress) Reset() {
	*x = QueryProgress{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProgress) ProtoMessage() {}

func (x *QueryProgress) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProgress.ProtoReflect.Descriptor instead.
func (*QueryProgress) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryProgress) GetRowsProcessed() int64 {
	if x != nil {
		return x.RowsProcessed
	}
	return 0
}

func (x *QueryProgress) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

func (x *QueryProgress) GetProgressPercentage() float64 {
	if x != nil {
		return x.ProgressPercentage
	}
	return 0
}

func (x *QueryProgress) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *QueryProgress) GetCurrentPhase() string {
	if x != nil {
		return x.CurrentPhase
	}
	return ""
}

func (x *QueryProgress) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metadata wrapper for oneof
type MetadataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*ColumnMetadata      `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataPayload) Reset() {
	*x = MetadataPayload{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataPayload) ProtoMessage() {}

func (x *MetadataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataPayload.ProtoReflect.Descriptor instead.
func (*MetadataPayload) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *MetadataPayload) GetColumns() []*ColumnMetadata {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Streaming query response
type StreamingQueryResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    StreamResponseType     `protobuf:"varint,1,opt,name=type,proto3,enum=sqlstudio.query.StreamResponseType" json:"type,omitempty"`
	QueryId string                 `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamingQueryResponse_Metadata
	//	*StreamingQueryResponse_Data
	//	*StreamingQueryResponse_Progress
	//	*StreamingQueryResponse_Completion
	//	*StreamingQueryResponse_Error
	Payload       isStreamingQueryResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingQueryResponse) Reset() {
	*x = StreamingQueryResponse{}
	mi := &file_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingQueryResponse) ProtoMessage() {}

func (x *StreamingQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingQueryResponse.ProtoReflect.Descriptor instead.
func (*StreamingQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{10}
}

func (x *StreamingQueryResponse) GetType() StreamResponseType {
	if x != nil {
		return x.Type
	}
	return StreamResponseType_STREAM_RESPONSE_TYPE_UNSPECIFIED
}

func (x *StreamingQueryResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *StreamingQueryResponse) GetPayload() isStreamingQueryResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamingQueryResponse) GetMetadata() *MetadataPayload {
	if x != nil {
		if x, ok := x.Payload.(*StreamingQueryResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *StreamingQueryResponse) GetData() *QueryRow {
	if x != nil {
		if x, ok := x.Payload.(*StreamingQueryResponse_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *StreamingQueryResponse) GetProgress() *QueryProgress {
	if x != nil {
		if x, ok := x.Payload.(*StreamingQueryResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *StreamingQueryResponse) GetCompletion() *QueryStats {
	if x != nil {
		if x, ok := x.Payload.(*StreamingQueryResponse_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

func (x *StreamingQueryResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*StreamingQueryResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isStreamingQueryResponse_Payload interface {
	isStreamingQueryResponse_Payload()
}

type StreamingQueryResponse_Metadata struct {
	Metadata *MetadataPayload `protobuf:"bytes,3,opt,name=metadata,proto3,oneof"`
}

type StreamingQueryResponse_Data struct {
	Data *QueryRow `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type StreamingQueryResponse_Progress struct {
	Progress *QueryProgress `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type StreamingQueryResponse_Completion struct {
	Completion *QueryStats `protobuf:"bytes,6,opt,name=completion,proto3,oneof"`
}

type StreamingQueryResponse_Error struct {
	Error string `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*StreamingQueryResponse_Metadata) isStreamingQueryResponse_Payload() {}

func (*StreamingQueryResponse_Data) isStreamingQueryResponse_Payload() {}

func (*StreamingQueryResponse_Progress) isStreamingQueryResponse_Payload() {}

func (*StreamingQueryResponse_Completion) isStreamingQueryResponse_Payload() {}

func (*StreamingQueryResponse_Error) isStreamingQueryResponse_Payload() {}

// Cancel query request
type CancelQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryRequest) Reset() {
	*x = CancelQueryRequest{}
	mi := &file_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryRequest) ProtoMessage() {}

func (x *CancelQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryRequest.ProtoReflect.Descriptor instead.
func (*CancelQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{11}
}

func (x *CancelQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

// Cancel query response
type CancelQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WasRunning    bool                   `protobuf:"varint,3,opt,name=was_running,json=wasRunning,proto3" json:"was_running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueryResponse) Reset() {
	*x = CancelQueryResponse{}
	mi := &file_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueryResponse) ProtoMessage() {}

func (x *CancelQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueryResponse.ProtoReflect.Descriptor instead.
func (*CancelQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{12}
}

func (x *CancelQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelQueryResponse) GetWasRunning() bool {
	if x != nil {
		return x.WasRunning
	}
	return false
}

// Get query status request
type GetQueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryStatusRequest) Reset() {
	*x = GetQueryStatusRequest{}
	mi := &file_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryStatusRequest) ProtoMessage() {}

func (x *GetQueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryStatusRequest.ProtoReflect.Descriptor instead.
func (*GetQueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{13}
}

func (x *GetQueryStatusRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

// Get query status response
type GetQueryStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        QueryStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=sqlstudio.query.QueryStatus" json:"status,omitempty"`
	Progress      *QueryProgress         `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryStatusResponse) Reset() {
	*x = GetQueryStatusResponse{}
	mi := &file_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryStatusResponse) ProtoMessage() {}

func (x *GetQueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryStatusResponse.ProtoReflect.Descriptor instead.
func (*GetQueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{14}
}

func (x *GetQueryStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQueryStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQueryStatusResponse) GetStatus() QueryStatus {
	if x != nil {
		return x.Status
	}
	return QueryStatus_QUERY_STATUS_UNSPECIFIED
}

func (x *GetQueryStatusResponse) GetProgress() *QueryProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetQueryStatusResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// List active queries request
type ListActiveQueriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // Optional filter
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveQueriesRequest) Reset() {
	*x = ListActiveQueriesRequest{}
	mi := &file_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveQueriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveQueriesRequest) ProtoMessage() {}

func (x *ListActiveQueriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveQueriesRequest.ProtoReflect.Descriptor instead.
func (*ListActiveQueriesRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{15}
}

func (x *ListActiveQueriesRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ListActiveQueriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Active query info
type ActiveQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sql           string                 `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`
	Status        QueryStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=sqlstudio.query.QueryStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Progress      *QueryProgress         `protobuf:"bytes,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveQuery) Reset() {
	*x = ActiveQuery{}
	mi := &file_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveQuery) ProtoMessage() {}

func (x *ActiveQuery) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveQuery.ProtoReflect.Descriptor instead.
func (*ActiveQuery) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{16}
}

func (x *ActiveQuery) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *ActiveQuery) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ActiveQuery) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActiveQuery) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ActiveQuery) GetStatus() QueryStatus {
	if x != nil {
		return x.Status
	}
	return QueryStatus_QUERY_STATUS_UNSPECIFIED
}

func (x *ActiveQuery) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ActiveQuery) GetProgress() *QueryProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

// List active queries response
type ListActiveQueriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Queries       []*ActiveQuery         `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveQueriesResponse) Reset() {
	*x = ListActiveQueriesResponse{}
	mi := &file_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveQueriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveQueriesResponse) ProtoMessage() {}

func (x *ListActiveQueriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveQueriesResponse.ProtoReflect.Descriptor instead.
func (*ListActiveQueriesResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{17}
}

func (x *ListActiveQueriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListActiveQueriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListActiveQueriesResponse) GetQueries() []*ActiveQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

// Batch edit operation
type BatchEditOperation struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	Id              string                           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type            BatchEditOperation_OperationType `protobuf:"varint,2,opt,name=type,proto3,enum=sqlstudio.query.BatchEditOperation_OperationType" json:"type,omitempty"`
	TableName       string                           `protobuf:"bytes,3,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	SchemaName      string                           `protobuf:"bytes,4,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	Values          map[string]*anypb.Any            `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	WhereConditions map[string]*anypb.Any            `protobuf:"bytes,6,rep,name=where_conditions,json=whereConditions,proto3" json:"where_conditions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Version         int64                            `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"` // For optimistic locking
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BatchEditOperation) Reset() {
	*x = BatchEditOperation{}
	mi := &file_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEditOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEditOperation) ProtoMessage() {}

func (x *BatchEditOperation) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEditOperation.ProtoReflect.Descriptor instead.
func (*BatchEditOperation) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{18}
}

func (x *BatchEditOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BatchEditOperation) GetType() BatchEditOperation_OperationType {
	if x != nil {
		return x.Type
	}
	return BatchEditOperation_OPERATION_TYPE_UNSPECIFIED
}

func (x *BatchEditOperation) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *BatchEditOperation) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *BatchEditOperation) GetValues() map[string]*anypb.Any {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *BatchEditOperation) GetWhereConditions() map[string]*anypb.Any {
	if x != nil {
		return x.WhereConditions
	}
	return nil
}

func (x *BatchEditOperation) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Execute batch edit request
type ExecuteBatchEditRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId   string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Operations     []*BatchEditOperation  `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	UseTransaction bool                   `protobuf:"varint,3,opt,name=use_transaction,json=useTransaction,proto3" json:"use_transaction,omitempty"`
	Options        *QueryOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteBatchEditRequest) Reset() {
	*x = ExecuteBatchEditRequest{}
	mi := &file_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchEditRequest) ProtoMessage() {}

func (x *ExecuteBatchEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchEditRequest.ProtoReflect.Descriptor instead.
func (*ExecuteBatchEditRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteBatchEditRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ExecuteBatchEditRequest) GetOperations() []*BatchEditOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ExecuteBatchEditRequest) GetUseTransaction() bool {
	if x != nil {
		return x.UseTransaction
	}
	return false
}

func (x *ExecuteBatchEditRequest) GetOptions() *QueryOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Batch edit result
type BatchEditResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	RowsAffected   int64                  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	ReturnedValues map[string]*anypb.Any  `protobuf:"bytes,5,rep,name=returned_values,json=returnedValues,proto3" json:"returned_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // For INSERT with RETURNING
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchEditResult) Reset() {
	*x = BatchEditResult{}
	mi := &file_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEditResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEditResult) ProtoMessage() {}

func (x *BatchEditResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEditResult.ProtoReflect.Descriptor instead.
func (*BatchEditResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{20}
}

func (x *BatchEditResult) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *BatchEditResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchEditResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchEditResult) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *BatchEditResult) GetReturnedValues() map[string]*anypb.Any {
	if x != nil {
		return x.ReturnedValues
	}
	return nil
}

// Execute batch edit response
type ExecuteBatchEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Results       []*BatchEditResult     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	TransactionId string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteBatchEditResponse) Reset() {
	*x = ExecuteBatchEditResponse{}
	mi := &file_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteBatchEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteBatchEditResponse) ProtoMessage() {}

func (x *ExecuteBatchEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteBatchEditResponse.ProtoReflect.Descriptor instead.
func (*ExecuteBatchEditResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteBatchEditResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteBatchEditResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteBatchEditResponse) GetResults() []*BatchEditResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ExecuteBatchEditResponse) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *ExecuteBatchEditResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// Get query history request
type GetQueryHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"` // Optional filter
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                   // Optional filter
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"` // For pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryHistoryRequest) Reset() {
	*x = GetQueryHistoryRequest{}
	mi := &file_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryHistoryRequest) ProtoMessage() {}

func (x *GetQueryHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetQueryHistoryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{22}
}

func (x *GetQueryHistoryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *GetQueryHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetQueryHistoryRequest) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *GetQueryHistoryRequest) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

func (x *GetQueryHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetQueryHistoryRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// Query history entry
type QueryHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	ConnectionId  string                 `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Sql           string                 `protobuf:"bytes,4,opt,name=sql,proto3" json:"sql,omitempty"`
	Status        QueryStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=sqlstudio.query.QueryStatus" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Stats         *QueryStats            `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryHistoryEntry) Reset() {
	*x = QueryHistoryEntry{}
	mi := &file_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryHistoryEntry) ProtoMessage() {}

func (x *QueryHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryHistoryEntry.ProtoReflect.Descriptor instead.
func (*QueryHistoryEntry) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{23}
}

func (x *QueryHistoryEntry) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryHistoryEntry) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *QueryHistoryEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryHistoryEntry) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryHistoryEntry) GetStatus() QueryStatus {
	if x != nil {
		return x.Status
	}
	return QueryStatus_QUERY_STATUS_UNSPECIFIED
}

func (x *QueryHistoryEntry) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *QueryHistoryEntry) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *QueryHistoryEntry) GetStats() *QueryStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *QueryHistoryEntry) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Get query history response
type GetQueryHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Entries       []*QueryHistoryEntry   `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,4,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,5,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryHistoryResponse) Reset() {
	*x = GetQueryHistoryResponse{}
	mi := &file_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryHistoryResponse) ProtoMessage() {}

func (x *GetQueryHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetQueryHistoryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{24}
}

func (x *GetQueryHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQueryHistoryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetQueryHistoryResponse) GetEntries() []*QueryHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetQueryHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetQueryHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

// Explain query request
type ExplainQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectionId  string                 `protobuf:"bytes,1,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    map[string]*anypb.Any  `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Analyze       bool                   `protobuf:"varint,4,opt,name=analyze,proto3" json:"analyze,omitempty"` // Include actual execution stats
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`    // JSON, TEXT, XML, YAML
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainQueryRequest) Reset() {
	*x = ExplainQueryRequest{}
	mi := &file_query_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainQueryRequest) ProtoMessage() {}

func (x *ExplainQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainQueryRequest.ProtoReflect.Descriptor instead.
func (*ExplainQueryRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{25}
}

func (x *ExplainQueryRequest) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ExplainQueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *ExplainQueryRequest) GetParameters() map[string]*anypb.Any {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExplainQueryRequest) GetAnalyze() bool {
	if x != nil {
		return x.Analyze
	}
	return false
}

func (x *ExplainQueryRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Query execution plan
type ExecutionPlan struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Format         string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Plan           string                 `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	EstimatedStats *QueryStats            `protobuf:"bytes,3,opt,name=estimated_stats,json=estimatedStats,proto3" json:"estimated_stats,omitempty"`
	ActualStats    *QueryStats            `protobuf:"bytes,4,opt,name=actual_stats,json=actualStats,proto3" json:"actual_stats,omitempty"` // If analyze=true
	Warnings       []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutionPlan) Reset() {
	*x = ExecutionPlan{}
	mi := &file_query_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPlan) ProtoMessage() {}

func (x *ExecutionPlan) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPlan.ProtoReflect.Descriptor instead.
func (*ExecutionPlan) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{26}
}

func (x *ExecutionPlan) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExecutionPlan) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *ExecutionPlan) GetEstimatedStats() *QueryStats {
	if x != nil {
		return x.EstimatedStats
	}
	return nil
}

func (x *ExecutionPlan) GetActualStats() *QueryStats {
	if x != nil {
		return x.ActualStats
	}
	return nil
}

func (x *ExecutionPlan) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// Explain query response
type ExplainQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Plan          *ExecutionPlan         `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainQueryResponse) Reset() {
	*x = ExplainQueryResponse{}
	mi := &file_query_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainQueryResponse) ProtoMessage() {}

func (x *ExplainQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainQueryResponse.ProtoReflect.Descriptor instead.
func (*ExplainQueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{27}
}

func (x *ExplainQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExplainQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExplainQueryResponse) GetPlan() *ExecutionPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x0fsqlstudio.query\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xcb\x02\n" +
	"\x13ExecuteQueryRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12T\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v24.sqlstudio.query.ExecuteQueryRequest.ParametersEntryR\n" +
	"parameters\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.sqlstudio.query.QueryOptionsR\aoptions\x12\x19\n" +
	"\bquery_id\x18\x05 \x01(\tR\aqueryId\x1aS\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x83\x02\n" +
	"\fQueryOptions\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\x12\x18\n" +
	"\aexplain\x18\x04 \x01(\bR\aexplain\x123\n" +
	"\x06format\x18\x05 \x01(\x0e2\x1b.sqlstudio.query.DataFormatR\x06format\x12)\n" +
	"\x10include_metadata\x18\x06 \x01(\bR\x0fincludeMetadata\x12\x1d\n" +
	"\n" +
	"fetch_size\x18\a \x01(\x05R\tfetchSize\"\xae\x01\n" +
	"\x0eColumnMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x18\n" +
	"\aordinal\x18\x04 \x01(\x05R\aordinal\x12\x1d\n" +
	"\n" +
	"table_name\x18\x05 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x06 \x01(\tR\n" +
	"schemaName\"8\n" +
	"\bQueryRow\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.google.protobuf.AnyR\x06values\"\xcf\x01\n" +
	"\vQueryResult\x129\n" +
	"\acolumns\x18\x01 \x03(\v2\x1f.sqlstudio.query.ColumnMetadataR\acolumns\x12-\n" +
	"\x04rows\x18\x02 \x03(\v2\x19.sqlstudio.query.QueryRowR\x04rows\x12\x1b\n" +
	"\trow_count\x18\x03 \x01(\x03R\browCount\x12!\n" +
	"\fmore_results\x18\x04 \x01(\bR\vmoreResults\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"\xc5\x03\n" +
	"\n" +
	"QueryStats\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\x12#\n" +
	"\rrows_returned\x18\x05 \x01(\x03R\frowsReturned\x12'\n" +
	"\x0fbytes_processed\x18\x06 \x01(\x03R\x0ebytesProcessed\x12%\n" +
	"\x0ebytes_returned\x18\a \x01(\x03R\rbytesReturned\x12\x1e\n" +
	"\vcpu_time_ms\x18\b \x01(\x01R\tcpuTimeMs\x12*\n" +
	"\x11memory_used_bytes\x18\t \x01(\x03R\x0fmemoryUsedBytes\x12\x1d\n" +
	"\n" +
	"disk_reads\x18\n" +
	" \x01(\x03R\tdiskReads\x12\x1f\n" +
	"\vdisk_writes\x18\v \x01(\x03R\n" +
	"diskWrites\"\xea\x01\n" +
	"\x14ExecuteQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x19\n" +
	"\bquery_id\x18\x03 \x01(\tR\aqueryId\x124\n" +
	"\x06result\x18\x04 \x01(\v2\x1c.sqlstudio.query.QueryResultR\x06result\x121\n" +
	"\x05stats\x18\x05 \x01(\v2\x1b.sqlstudio.query.QueryStatsR\x05stats\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\"\xdd\x02\n" +
	"\x1cExecuteStreamingQueryRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12]\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2=.sqlstudio.query.ExecuteStreamingQueryRequest.ParametersEntryR\n" +
	"parameters\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.sqlstudio.query.QueryOptionsR\aoptions\x12\x19\n" +
	"\bquery_id\x18\x05 \x01(\tR\aqueryId\x1aS\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xeb\x02\n" +
	"\rQueryProgress\x12%\n" +
	"\x0erows_processed\x18\x01 \x01(\x03R\rrowsProcessed\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x02 \x01(\x03R\ttotalRows\x12/\n" +
	"\x13progress_percentage\x18\x03 \x01(\x01R\x12progressPercentage\x12;\n" +
	"\vlast_update\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12#\n" +
	"\rcurrent_phase\x18\x05 \x01(\tR\fcurrentPhase\x12E\n" +
	"\ametrics\x18\x06 \x03(\v2+.sqlstudio.query.QueryProgress.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x0fMetadataPayload\x129\n" +
	"\acolumns\x18\x01 \x03(\v2\x1f.sqlstudio.query.ColumnMetadataR\acolumns\"\xfd\x02\n" +
	"\x16StreamingQueryResponse\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.sqlstudio.query.StreamResponseTypeR\x04type\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\tR\aqueryId\x12>\n" +
	"\bmetadata\x18\x03 \x01(\v2 .sqlstudio.query.MetadataPayloadH\x00R\bmetadata\x12/\n" +
	"\x04data\x18\x04 \x01(\v2\x19.sqlstudio.query.QueryRowH\x00R\x04data\x12<\n" +
	"\bprogress\x18\x05 \x01(\v2\x1e.sqlstudio.query.QueryProgressH\x00R\bprogress\x12=\n" +
	"\n" +
	"completion\x18\x06 \x01(\v2\x1b.sqlstudio.query.QueryStatsH\x00R\n" +
	"completion\x12\x16\n" +
	"\x05error\x18\a \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"/\n" +
	"\x12CancelQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\"j\n" +
	"\x13CancelQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vwas_running\x18\x03 \x01(\bR\n" +
	"wasRunning\"2\n" +
	"\x15GetQueryStatusRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\"\xf1\x01\n" +
	"\x16GetQueryStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.sqlstudio.query.QueryStatusR\x06status\x12:\n" +
	"\bprogress\x18\x04 \x01(\v2\x1e.sqlstudio.query.QueryProgressR\bprogress\x121\n" +
	"\x05stats\x18\x05 \x01(\v2\x1b.sqlstudio.query.QueryStatsR\x05stats\"X\n" +
	"\x18ListActiveQueriesRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa5\x02\n" +
	"\vActiveQuery\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03sql\x18\x04 \x01(\tR\x03sql\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.sqlstudio.query.QueryStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bprogress\x18\a \x01(\v2\x1e.sqlstudio.query.QueryProgressR\bprogress\"\x87\x01\n" +
	"\x19ListActiveQueriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\aqueries\x18\x03 \x03(\v2\x1c.sqlstudio.query.ActiveQueryR\aqueries\"\xa1\x05\n" +
	"\x12BatchEditOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x04type\x18\x02 \x01(\x0e21.sqlstudio.query.BatchEditOperation.OperationTypeR\x04type\x12\x1d\n" +
	"\n" +
	"table_name\x18\x03 \x01(\tR\ttableName\x12\x1f\n" +
	"\vschema_name\x18\x04 \x01(\tR\n" +
	"schemaName\x12G\n" +
	"\x06values\x18\x05 \x03(\v2/.sqlstudio.query.BatchEditOperation.ValuesEntryR\x06values\x12c\n" +
	"\x10where_conditions\x18\x06 \x03(\v28.sqlstudio.query.BatchEditOperation.WhereConditionsEntryR\x0fwhereConditions\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\x1aX\n" +
	"\x14WhereConditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x80\x01\n" +
	"\rOperationType\x12\x1e\n" +
	"\x1aOPERATION_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OPERATION_TYPE_INSERT\x10\x01\x12\x19\n" +
	"\x15OPERATION_TYPE_UPDATE\x10\x02\x12\x19\n" +
	"\x15OPERATION_TYPE_DELETE\x10\x03\"\xe5\x01\n" +
	"\x17ExecuteBatchEditRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12C\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2#.sqlstudio.query.BatchEditOperationR\n" +
	"operations\x12'\n" +
	"\x0fuse_transaction\x18\x03 \x01(\bR\x0euseTransaction\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.sqlstudio.query.QueryOptionsR\aoptions\"\xc5\x02\n" +
	"\x0fBatchEditResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\x12]\n" +
	"\x0freturned_values\x18\x05 \x03(\v24.sqlstudio.query.BatchEditResult.ReturnedValuesEntryR\x0ereturnedValues\x1aW\n" +
	"\x13ReturnedValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x18ExecuteBatchEditResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\aresults\x18\x03 \x03(\v2 .sqlstudio.query.BatchEditResultR\aresults\x121\n" +
	"\x05stats\x18\x04 \x01(\v2\x1b.sqlstudio.query.QueryStatsR\x05stats\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\"\xf2\x01\n" +
	"\x16GetQueryHistoryRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\tfrom_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\"\x86\x03\n" +
	"\x11QueryHistoryEntry\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12#\n" +
	"\rconnection_id\x18\x02 \x01(\tR\fconnectionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x10\n" +
	"\x03sql\x18\x04 \x01(\tR\x03sql\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.sqlstudio.query.QueryStatusR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x121\n" +
	"\x05stats\x18\b \x01(\v2\x1b.sqlstudio.query.QueryStatsR\x05stats\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"\xc7\x01\n" +
	"\x17GetQueryHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\aentries\x18\x03 \x03(\v2\".sqlstudio.query.QueryHistoryEntryR\aentries\x12\x1f\n" +
	"\vnext_cursor\x18\x04 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x05 \x01(\bR\ahasMore\"\xa9\x02\n" +
	"\x13ExplainQueryRequest\x12#\n" +
	"\rconnection_id\x18\x01 \x01(\tR\fconnectionId\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x12T\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v24.sqlstudio.query.ExplainQueryRequest.ParametersEntryR\n" +
	"parameters\x12\x18\n" +
	"\aanalyze\x18\x04 \x01(\bR\aanalyze\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\x1aS\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xdd\x01\n" +
	"\rExecutionPlan\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x12\n" +
	"\x04plan\x18\x02 \x01(\tR\x04plan\x12D\n" +
	"\x0festimated_stats\x18\x03 \x01(\v2\x1b.sqlstudio.query.QueryStatsR\x0eestimatedStats\x12>\n" +
	"\factual_stats\x18\x04 \x01(\v2\x1b.sqlstudio.query.QueryStatsR\vactualStats\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"~\n" +
	"\x14ExplainQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04plan\x18\x03 \x01(\v2\x1e.sqlstudio.query.ExecutionPlanR\x04plan*\xcb\x01\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11QUERY_TYPE_SELECT\x10\x01\x12\x15\n" +
	"\x11QUERY_TYPE_INSERT\x10\x02\x12\x15\n" +
	"\x11QUERY_TYPE_UPDATE\x10\x03\x12\x15\n" +
	"\x11QUERY_TYPE_DELETE\x10\x04\x12\x12\n" +
	"\x0eQUERY_TYPE_DDL\x10\x05\x12\x1a\n" +
	"\x16QUERY_TYPE_TRANSACTION\x10\x06\x12\x16\n" +
	"\x12QUERY_TYPE_EXPLAIN\x10\a*\x85\x01\n" +
	"\rExecutionMode\x12\x1e\n" +
	"\x1aEXECUTION_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18EXECUTION_MODE_IMMEDIATE\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_MODE_STREAMING\x10\x02\x12\x18\n" +
	"\x14EXECUTION_MODE_BATCH\x10\x03*\x86\x01\n" +
	"\n" +
	"DataFormat\x12\x1b\n" +
	"\x17DATA_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DATA_FORMAT_JSON\x10\x01\x12\x16\n" +
	"\x12DATA_FORMAT_NDJSON\x10\x02\x12\x13\n" +
	"\x0fDATA_FORMAT_CSV\x10\x03\x12\x18\n" +
	"\x14DATA_FORMAT_PROTOBUF\x10\x04*\xe2\x01\n" +
	"\x12StreamResponseType\x12$\n" +
	" STREAM_RESPONSE_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSTREAM_RESPONSE_TYPE_METADATA\x10\x01\x12\x1d\n" +
	"\x19STREAM_RESPONSE_TYPE_DATA\x10\x02\x12!\n" +
	"\x1dSTREAM_RESPONSE_TYPE_PROGRESS\x10\x03\x12!\n" +
	"\x1dSTREAM_RESPONSE_TYPE_COMPLETE\x10\x04\x12\x1e\n" +
	"\x1aSTREAM_RESPONSE_TYPE_ERROR\x10\x05*\xb0\x01\n" +
	"\vQueryStatus\x12\x1c\n" +
	"\x18QUERY_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14QUERY_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14QUERY_STATUS_RUNNING\x10\x02\x12\x1a\n" +
	"\x16QUERY_STATUS_COMPLETED\x10\x03\x12\x17\n" +
	"\x13QUERY_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16QUERY_STATUS_CANCELLED\x10\x052\xb3\x06\n" +
	"\fQueryService\x12[\n" +
	"\fExecuteQuery\x12$.sqlstudio.query.ExecuteQueryRequest\x1a%.sqlstudio.query.ExecuteQueryResponse\x12q\n" +
	"\x15ExecuteStreamingQuery\x12-.sqlstudio.query.ExecuteStreamingQueryRequest\x1a'.sqlstudio.query.StreamingQueryResponse0\x01\x12X\n" +
	"\vCancelQuery\x12#.sqlstudio.query.CancelQueryRequest\x1a$.sqlstudio.query.CancelQueryResponse\x12a\n" +
	"\x0eGetQueryStatus\x12&.sqlstudio.query.GetQueryStatusRequest\x1a'.sqlstudio.query.GetQueryStatusResponse\x12j\n" +
	"\x11ListActiveQueries\x12).sqlstudio.query.ListActiveQueriesRequest\x1a*.sqlstudio.query.ListActiveQueriesResponse\x12g\n" +
	"\x10ExecuteBatchEdit\x12(.sqlstudio.query.ExecuteBatchEditRequest\x1a).sqlstudio.query.ExecuteBatchEditResponse\x12d\n" +
	"\x0fGetQueryHistory\x12'.sqlstudio.query.GetQueryHistoryRequest\x1a(.sqlstudio.query.GetQueryHistoryResponse\x12[\n" +
	"\fExplainQuery\x12$.sqlstudio.query.ExplainQueryRequest\x1a%.sqlstudio.query.ExplainQueryResponseB,Z*github.com/sql-studio/backend-go/api/queryb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_query_proto_goTypes = []any{
	(QueryType)(0),                        // 0: sqlstudio.query.QueryType
	(ExecutionMode)(0),                    // 1: sqlstudio.query.ExecutionMode
	(DataFormat)(0),                       // 2: sqlstudio.query.DataFormat
	(StreamResponseType)(0),               // 3: sqlstudio.query.StreamResponseType
	(QueryStatus)(0),                      // 4: sqlstudio.query.QueryStatus
	(BatchEditOperation_OperationType)(0), // 5: sqlstudio.query.BatchEditOperation.OperationType
	(*ExecuteQueryRequest)(nil),           // 6: sqlstudio.query.ExecuteQueryRequest
	(*QueryOptions)(nil),                  // 7: sqlstudio.query.QueryOptions
	(*ColumnMetadata)(nil),                // 8: sqlstudio.query.ColumnMetadata
	(*QueryRow)(nil),                      // 9: sqlstudio.query.QueryRow
	(*QueryResult)(nil),                   // 10: sqlstudio.query.QueryResult
	(*QueryStats)(nil),                    // 11: sqlstudio.query.QueryStats
	(*ExecuteQueryResponse)(nil),          // 12: sqlstudio.query.ExecuteQueryResponse
	(*ExecuteStreamingQueryRequest)(nil),  // 13: sqlstudio.query.ExecuteStreamingQueryRequest
	(*QueryProgress)(nil),                 // 14: sqlstudio.query.QueryProgress
	(*MetadataPayload)(nil),               // 15: sqlstudio.query.MetadataPayload
	(*StreamingQueryResponse)(nil),        // 16: sqlstudio.query.StreamingQueryResponse
	(*CancelQueryRequest)(nil),            // 17: sqlstudio.query.CancelQueryRequest
	(*CancelQueryResponse)(nil),           // 18: sqlstudio.query.CancelQueryResponse
	(*GetQueryStatusRequest)(nil),         // 19: sqlstudio.query.GetQueryStatusRequest
	(*GetQueryStatusResponse)(nil),        // 20: sqlstudio.query.GetQueryStatusResponse
	(*ListActiveQueriesRequest)(nil),      // 21: sqlstudio.query.ListActiveQueriesRequest
	(*ActiveQuery)(nil),                   // 22: sqlstudio.query.ActiveQuery
	(*ListActiveQueriesResponse)(nil),     // 23: sqlstudio.query.ListActiveQueriesResponse
	(*BatchEditOperation)(nil),            // 24: sqlstudio.query.BatchEditOperation
	(*ExecuteBatchEditRequest)(nil),       // 25: sqlstudio.query.ExecuteBatchEditRequest
	(*BatchEditResult)(nil),               // 26: sqlstudio.query.BatchEditResult
	(*ExecuteBatchEditResponse)(nil),      // 27: sqlstudio.query.ExecuteBatchEditResponse
	(*GetQueryHistoryRequest)(nil),        // 28: sqlstudio.query.GetQueryHistoryRequest
	(*QueryHistoryEntry)(nil),             // 29: sqlstudio.query.QueryHistoryEntry
	(*GetQueryHistoryResponse)(nil),       // 30: sqlstudio.query.GetQueryHistoryResponse
	(*ExplainQueryRequest)(nil),           // 31: sqlstudio.query.ExplainQueryRequest
	(*ExecutionPlan)(nil),                 // 32: sqlstudio.query.ExecutionPlan
	(*ExplainQueryResponse)(nil),          // 33: sqlstudio.query.ExplainQueryResponse
	nil,                                   // 34: sqlstudio.query.ExecuteQueryRequest.ParametersEntry
	nil,                                   // 35: sqlstudio.query.ExecuteStreamingQueryRequest.ParametersEntry
	nil,                                   // 36: sqlstudio.query.QueryProgress.MetricsEntry
	nil,                                   // 37: sqlstudio.query.BatchEditOperation.ValuesEntry
	nil,                                   // 38: sqlstudio.query.BatchEditOperation.WhereConditionsEntry
	nil,                                   // 39: sqlstudio.query.BatchEditResult.ReturnedValuesEntry
	nil,                                   // 40: sqlstudio.query.ExplainQueryRequest.ParametersEntry
	(*anypb.Any)(nil),                     // 41: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),         // 42: google.protobuf.Timestamp
}
var file_query_proto_depIdxs = []int32{
	34, // 0: sqlstudio.query.ExecuteQueryRequest.parameters:type_name -> sqlstudio.query.ExecuteQueryRequest.ParametersEntry
	7,  // 1: sqlstudio.query.ExecuteQueryRequest.options:type_name -> sqlstudio.query.QueryOptions
	2,  // 2: sqlstudio.query.QueryOptions.format:type_name -> sqlstudio.query.DataFormat
	41, // 3: sqlstudio.query.QueryRow.values:type_name -> google.protobuf.Any
	8,  // 4: sqlstudio.query.QueryResult.columns:type_name -> sqlstudio.query.ColumnMetadata
	9,  // 5: sqlstudio.query.QueryResult.rows:type_name -> sqlstudio.query.QueryRow
	42, // 6: sqlstudio.query.QueryStats.start_time:type_name -> google.protobuf.Timestamp
	42, // 7: sqlstudio.query.QueryStats.end_time:type_name -> google.protobuf.Timestamp
	10, // 8: sqlstudio.query.ExecuteQueryResponse.result:type_name -> sqlstudio.query.QueryResult
	11, // 9: sqlstudio.query.ExecuteQueryResponse.stats:type_name -> sqlstudio.query.QueryStats
	35, // 10: sqlstudio.query.ExecuteStreamingQueryRequest.parameters:type_name -> sqlstudio.query.ExecuteStreamingQueryRequest.ParametersEntry
	7,  // 11: sqlstudio.query.ExecuteStreamingQueryRequest.options:type_name -> sqlstudio.query.QueryOptions
	42, // 12: sqlstudio.query.QueryProgress.last_update:type_name -> google.protobuf.Timestamp
	36, // 13: sqlstudio.query.QueryProgress.metrics:type_name -> sqlstudio.query.QueryProgress.MetricsEntry
	8,  // 14: sqlstudio.query.MetadataPayload.columns:type_name -> sqlstudio.query.ColumnMetadata
	3,  // 15: sqlstudio.query.StreamingQueryResponse.type:type_name -> sqlstudio.query.StreamResponseType
	15, // 16: sqlstudio.query.StreamingQueryResponse.metadata:type_name -> sqlstudio.query.MetadataPayload
	9,  // 17: sqlstudio.query.StreamingQueryResponse.data:type_name -> sqlstudio.query.QueryRow
	14, // 18: sqlstudio.query.StreamingQueryResponse.progress:type_name -> sqlstudio.query.QueryProgress
	11, // 19: sqlstudio.query.StreamingQueryResponse.completion:type_name -> sqlstudio.query.QueryStats
	4,  // 20: sqlstudio.query.GetQueryStatusResponse.status:type_name -> sqlstudio.query.QueryStatus
	14, // 21: sqlstudio.query.GetQueryStatusResponse.progress:type_name -> sqlstudio.query.QueryProgress
	11, // 22: sqlstudio.query.GetQueryStatusResponse.stats:type_name -> sqlstudio.query.QueryStats
	4,  // 23: sqlstudio.query.ActiveQuery.status:type_name -> sqlstudio.query.QueryStatus
	42, // 24: sqlstudio.query.ActiveQuery.started_at:type_name -> google.protobuf.Timestamp
	14, // 25: sqlstudio.query.ActiveQuery.progress:type_name -> sqlstudio.query.QueryProgress
	22, // 26: sqlstudio.query.ListActiveQueriesResponse.queries:type_name -> sqlstudio.query.ActiveQuery
	5,  // 27: sqlstudio.query.BatchEditOperation.type:type_name -> sqlstudio.query.BatchEditOperation.OperationType
	37, // 28: sqlstudio.query.BatchEditOperation.values:type_name -> sqlstudio.query.BatchEditOperation.ValuesEntry
	38, // 29: sqlstudio.query.BatchEditOperation.where_conditions:type_name -> sqlstudio.query.BatchEditOperation.WhereConditionsEntry
	24, // 30: sqlstudio.query.ExecuteBatchEditRequest.operations:type_name -> sqlstudio.query.BatchEditOperation
	7,  // 31: sqlstudio.query.ExecuteBatchEditRequest.options:type_name -> sqlstudio.query.QueryOptions
	39, // 32: sqlstudio.query.BatchEditResult.returned_values:type_name -> sqlstudio.query.BatchEditResult.ReturnedValuesEntry
	26, // 33: sqlstudio.query.ExecuteBatchEditResponse.results:type_name -> sqlstudio.query.BatchEditResult
	11, // 34: sqlstudio.query.ExecuteBatchEditResponse.stats:type_name -> sqlstudio.query.QueryStats
	42, // 35: sqlstudio.query.GetQueryHistoryRequest.from_time:type_name -> google.protobuf.Timestamp
	42, // 36: sqlstudio.query.GetQueryHistoryRequest.to_time:type_name -> google.protobuf.Timestamp
	4,  // 37: sqlstudio.query.QueryHistoryEntry.status:type_name -> sqlstudio.query.QueryStatus
	42, // 38: sqlstudio.query.QueryHistoryEntry.started_at:type_name -> google.protobuf.Timestamp
	42, // 39: sqlstudio.query.QueryHistoryEntry.completed_at:type_name -> google.protobuf.Timestamp
	11, // 40: sqlstudio.query.QueryHistoryEntry.stats:type_name -> sqlstudio.query.QueryStats
	29, // 41: sqlstudio.query.GetQueryHistoryResponse.entries:type_name -> sqlstudio.query.QueryHistoryEntry
	40, // 42: sqlstudio.query.ExplainQueryRequest.parameters:type_name -> sqlstudio.query.ExplainQueryRequest.ParametersEntry
	11, // 43: sqlstudio.query.ExecutionPlan.estimated_stats:type_name -> sqlstudio.query.QueryStats
	11, // 44: sqlstudio.query.ExecutionPlan.actual_stats:type_name -> sqlstudio.query.QueryStats
	32, // 45: sqlstudio.query.ExplainQueryResponse.plan:type_name -> sqlstudio.query.ExecutionPlan
	41, // 46: sqlstudio.query.ExecuteQueryRequest.ParametersEntry.value:type_name -> google.protobuf.Any
	41, // 47: sqlstudio.query.ExecuteStreamingQueryRequest.ParametersEntry.value:type_name -> google.protobuf.Any
	41, // 48: sqlstudio.query.BatchEditOperation.ValuesEntry.value:type_name -> google.protobuf.Any
	41, // 49: sqlstudio.query.BatchEditOperation.WhereConditionsEntry.value:type_name -> google.protobuf.Any
	41, // 50: sqlstudio.query.BatchEditResult.ReturnedValuesEntry.value:type_name -> google.protobuf.Any
	41, // 51: sqlstudio.query.ExplainQueryRequest.ParametersEntry.value:type_name -> google.protobuf.Any
	6,  // 52: sqlstudio.query.QueryService.ExecuteQuery:input_type -> sqlstudio.query.ExecuteQueryRequest
	13, // 53: sqlstudio.query.QueryService.ExecuteStreamingQuery:input_type -> sqlstudio.query.ExecuteStreamingQueryRequest
	17, // 54: sqlstudio.query.QueryService.CancelQuery:input_type -> sqlstudio.query.CancelQueryRequest
	19, // 55: sqlstudio.query.QueryService.GetQueryStatus:input_type -> sqlstudio.query.GetQueryStatusRequest
	21, // 56: sqlstudio.query.QueryService.ListActiveQueries:input_type -> sqlstudio.query.ListActiveQueriesRequest
	25, // 57: sqlstudio.query.QueryService.ExecuteBatchEdit:input_type -> sqlstudio.query.ExecuteBatchEditRequest
	28, // 58: sqlstudio.query.QueryService.GetQueryHistory:input_type -> sqlstudio.query.GetQueryHistoryRequest
	31, // 59: sqlstudio.query.QueryService.ExplainQuery:input_type -> sqlstudio.query.ExplainQueryRequest
	12, // 60: sqlstudio.query.QueryService.ExecuteQuery:output_type -> sqlstudio.query.ExecuteQueryResponse
	16, // 61: sqlstudio.query.QueryService.ExecuteStreamingQuery:output_type -> sqlstudio.query.StreamingQueryResponse
	18, // 62: sqlstudio.query.QueryService.CancelQuery:output_type -> sqlstudio.query.CancelQueryResponse
	20, // 63: sqlstudio.query.QueryService.GetQueryStatus:output_type -> sqlstudio.query.GetQueryStatusResponse
	23, // 64: sqlstudio.query.QueryService.ListActiveQueries:output_type -> sqlstudio.query.ListActiveQueriesResponse
	27, // 65: sqlstudio.query.QueryService.ExecuteBatchEdit:output_type -> sqlstudio.query.ExecuteBatchEditResponse
	30, // 66: sqlstudio.query.QueryService.GetQueryHistory:output_type -> sqlstudio.query.GetQueryHistoryResponse
	33, // 67: sqlstudio.query.QueryService.ExplainQuery:output_type -> sqlstudio.query.ExplainQueryResponse
	60, // [60:68] is the sub-list for method output_type
	52, // [52:60] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	file_query_proto_msgTypes[10].OneofWrappers = []any{
		(*StreamingQueryResponse_Metadata)(nil),
		(*StreamingQueryResponse_Data)(nil),
		(*StreamingQueryResponse_Progress)(nil),
		(*StreamingQueryResponse_Completion)(nil),
		(*StreamingQueryResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		EnumInfos:         file_query_proto_enumTypes,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
