// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: query.proto

package query

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueryService_ExecuteQuery_FullMethodName          = "/sqlstudio.query.QueryService/ExecuteQuery"
	QueryService_ExecuteStreamingQuery_FullMethodName = "/sqlstudio.query.QueryService/ExecuteStreamingQuery"
	QueryService_CancelQuery_FullMethodName           = "/sqlstudio.query.QueryService/CancelQuery"
	QueryService_GetQueryStatus_FullMethodName        = "/sqlstudio.query.QueryService/GetQueryStatus"
	QueryService_ListActiveQueries_FullMethodName     = "/sqlstudio.query.QueryService/ListActiveQueries"
	QueryService_ExecuteBatchEdit_FullMethodName      = "/sqlstudio.query.QueryService/ExecuteBatchEdit"
	QueryService_GetQueryHistory_FullMethodName       = "/sqlstudio.query.QueryService/GetQueryHistory"
	QueryService_ExplainQuery_FullMethodName          = "/sqlstudio.query.QueryService/ExplainQuery"
)

// QueryServiceClient is the client API for QueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Query service definition
type QueryServiceClient interface {
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	ExecuteStreamingQuery(ctx context.Context, in *ExecuteStreamingQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamingQueryResponse], error)
	CancelQuery(ctx context.Context, in *CancelQueryRequest, opts ...grpc.CallOption) (*CancelQueryResponse, error)
	GetQueryStatus(ctx context.Context, in *GetQueryStatusRequest, opts ...grpc.CallOption) (*GetQueryStatusResponse, error)
	ListActiveQueries(ctx context.Context, in *ListActiveQueriesRequest, opts ...grpc.CallOption) (*ListActiveQueriesResponse, error)
	ExecuteBatchEdit(ctx context.Context, in *ExecuteBatchEditRequest, opts ...grpc.CallOption) (*ExecuteBatchEditResponse, error)
	GetQueryHistory(ctx context.Context, in *GetQueryHistoryRequest, opts ...grpc.CallOption) (*GetQueryHistoryResponse, error)
	ExplainQuery(ctx context.Context, in *ExplainQueryRequest, opts ...grpc.CallOption) (*ExplainQueryResponse, error)
}

type queryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryServiceClient(cc grpc.ClientConnInterface) QueryServiceClient {
	return &queryServiceClient{cc}
}

func (c *queryServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, QueryService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ExecuteStreamingQuery(ctx context.Context, in *ExecuteStreamingQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamingQueryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueryService_ServiceDesc.Streams[0], QueryService_ExecuteStreamingQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteStreamingQueryRequest, StreamingQueryResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_ExecuteStreamingQueryClient = grpc.ServerStreamingClient[StreamingQueryResponse]

func (c *queryServiceClient) CancelQuery(ctx context.Context, in *CancelQueryRequest, opts ...grpc.CallOption) (*CancelQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelQueryResponse)
	err := c.cc.Invoke(ctx, QueryService_CancelQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetQueryStatus(ctx context.Context, in *GetQueryStatusRequest, opts ...grpc.CallOption) (*GetQueryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueryStatusResponse)
	err := c.cc.Invoke(ctx, QueryService_GetQueryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ListActiveQueries(ctx context.Context, in *ListActiveQueriesRequest, opts ...grpc.CallOption) (*ListActiveQueriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveQueriesResponse)
	err := c.cc.Invoke(ctx, QueryService_ListActiveQueries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ExecuteBatchEdit(ctx context.Context, in *ExecuteBatchEditRequest, opts ...grpc.CallOption) (*ExecuteBatchEditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBatchEditResponse)
	err := c.cc.Invoke(ctx, QueryService_ExecuteBatchEdit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) GetQueryHistory(ctx context.Context, in *GetQueryHistoryRequest, opts ...grpc.CallOption) (*GetQueryHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueryHistoryResponse)
	err := c.cc.Invoke(ctx, QueryService_GetQueryHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryServiceClient) ExplainQuery(ctx context.Context, in *ExplainQueryRequest, opts ...grpc.CallOption) (*ExplainQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainQueryResponse)
	err := c.cc.Invoke(ctx, QueryService_ExplainQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServiceServer is the server API for QueryService service.
// All implementations must embed UnimplementedQueryServiceServer
// for forward compatibility.
//
// Query service definition
type QueryServiceServer interface {
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	ExecuteStreamingQuery(*ExecuteStreamingQueryRequest, grpc.ServerStreamingServer[StreamingQueryResponse]) error
	CancelQuery(context.Context, *CancelQueryRequest) (*CancelQueryResponse, error)
	GetQueryStatus(context.Context, *GetQueryStatusRequest) (*GetQueryStatusResponse, error)
	ListActiveQueries(context.Context, *ListActiveQueriesRequest) (*ListActiveQueriesResponse, error)
	ExecuteBatchEdit(context.Context, *ExecuteBatchEditRequest) (*ExecuteBatchEditResponse, error)
	GetQueryHistory(context.Context, *GetQueryHistoryRequest) (*GetQueryHistoryResponse, error)
	ExplainQuery(context.Context, *ExplainQueryRequest) (*ExplainQueryResponse, error)
	mustEmbedUnimplementedQueryServiceServer()
}

// UnimplementedQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServiceServer struct{}

func (UnimplementedQueryServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedQueryServiceServer) ExecuteStreamingQuery(*ExecuteStreamingQueryRequest, grpc.ServerStreamingServer[StreamingQueryResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteStreamingQuery not implemented")
}
func (UnimplementedQueryServiceServer) CancelQuery(context.Context, *CancelQueryRequest) (*CancelQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelQuery not implemented")
}
func (UnimplementedQueryServiceServer) GetQueryStatus(context.Context, *GetQueryStatusRequest) (*GetQueryStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueryStatus not implemented")
}
func (UnimplementedQueryServiceServer) ListActiveQueries(context.Context, *ListActiveQueriesRequest) (*ListActiveQueriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveQueries not implemented")
}
func (UnimplementedQueryServiceServer) ExecuteBatchEdit(context.Context, *ExecuteBatchEditRequest) (*ExecuteBatchEditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBatchEdit not implemented")
}
func (UnimplementedQueryServiceServer) GetQueryHistory(context.Context, *GetQueryHistoryRequest) (*GetQueryHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueryHistory not implemented")
}
func (UnimplementedQueryServiceServer) ExplainQuery(context.Context, *ExplainQueryRequest) (*ExplainQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainQuery not implemented")
}
func (UnimplementedQueryServiceServer) mustEmbedUnimplementedQueryServiceServer() {}
func (UnimplementedQueryServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServiceServer will
// result in compilation errors.
type UnsafeQueryServiceServer interface {
	mustEmbedUnimplementedQueryServiceServer()
}

func RegisterQueryServiceServer(s grpc.ServiceRegistrar, srv QueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueryService_ServiceDesc, srv)
}

func _QueryService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ExecuteStreamingQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteStreamingQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServiceServer).ExecuteStreamingQuery(m, &grpc.GenericServerStream[ExecuteStreamingQueryRequest, StreamingQueryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueryService_ExecuteStreamingQueryServer = grpc.ServerStreamingServer[StreamingQueryResponse]

func _QueryService_CancelQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).CancelQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_CancelQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).CancelQuery(ctx, req.(*CancelQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetQueryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetQueryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetQueryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetQueryStatus(ctx, req.(*GetQueryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ListActiveQueries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveQueriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ListActiveQueries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ListActiveQueries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ListActiveQueries(ctx, req.(*ListActiveQueriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ExecuteBatchEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBatchEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ExecuteBatchEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ExecuteBatchEdit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ExecuteBatchEdit(ctx, req.(*ExecuteBatchEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_GetQueryHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).GetQueryHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_GetQueryHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).GetQueryHistory(ctx, req.(*GetQueryHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryService_ExplainQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServiceServer).ExplainQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryService_ExplainQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServiceServer).ExplainQuery(ctx, req.(*ExplainQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryService_ServiceDesc is the grpc.ServiceDesc for QueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sqlstudio.query.QueryService",
	HandlerType: (*QueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _QueryService_ExecuteQuery_Handler,
		},
		{
			MethodName: "CancelQuery",
			Handler:    _QueryService_CancelQuery_Handler,
		},
		{
			MethodName: "GetQueryStatus",
			Handler:    _QueryService_GetQueryStatus_Handler,
		},
		{
			MethodName: "ListActiveQueries",
			Handler:    _QueryService_ListActiveQueries_Handler,
		},
		{
			MethodName: "ExecuteBatchEdit",
			Handler:    _QueryService_ExecuteBatchEdit_Handler,
		},
		{
			MethodName: "GetQueryHistory",
			Handler:    _QueryService_GetQueryHistory_Handler,
		},
		{
			MethodName: "ExplainQuery",
			Handler:    _QueryService_ExplainQuery_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteStreamingQuery",
			Handler:       _QueryService_ExecuteStreamingQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "query.proto",
}
