# =============================================================================
# golangci-lint Configuration v2 for Howlerops Backend
# =============================================================================
# This configuration enables comprehensive linting with sensible defaults for
# production Go applications. It balances code quality with practicality.
#
# Run locally: golangci-lint run
# Run with auto-fix: golangci-lint run --fix
# =============================================================================

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - ineffassign
    - errcheck
    - gosec
    - nilerr

  disable:
    # Disable linters that are enabled by default in v2 but not needed for our minimal set
    - staticcheck  # Advanced static analysis - too many issues for current codebase
    - unused       # Unused code detection - too strict for development

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*database/sql.DB).Close
        - (*database/sql.Tx).Rollback
        - (*net/http.Response.Body).Close
        - (*os.File).Close
        - (*compress/gzip.Writer).Close
        - (*compress/gzip.Reader).Close
        - (*encoding/json.Encoder).Encode
        - (net/http.ResponseWriter).Write
        - (*net/http.Response.Body).Read
        - (*database/sql.Row).Scan
        - encoding/json.Unmarshal
        - os.Setenv
        - crypto/rand.Read
        - (*github.com/sirupsen/logrus.Entry).Log
        - (*github.com/sirupsen/logrus.Logger).Log

    govet:
      # Use default analyzers (35 well-balanced checks)
      # See GOLANGCI_LINT_V2_ANALYSIS.md for full analyzer list and rationale
      # Note: fieldalignment and shadow are disabled by default in govet

    gosec:
      excludes:
        - G104  # Audit errors not checked (covered by errcheck)
        - G304  # File path from user input (intentional for file operations)
      severity: medium
      confidence: medium

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party
      - testdata
      - examples
      - ".github"
    rules:
      - linters:
          - errcheck
          - gosec
          - goconst
        path: "_test\\.go"

severity:
  default: error

# =============================================================================
# Usage Examples
# =============================================================================
# Run all enabled linters:
#   golangci-lint run
#
# Run with auto-fix:
#   golangci-lint run --fix
#
# Run only fast linters:
#   golangci-lint run --fast
#
# Run on specific path:
#   golangci-lint run ./internal/...
#
# Generate report in different format:
#   golangci-lint run --out-format=json > report.json
#   golangci-lint run --out-format=checkstyle > report.xml
#
# Run with verbose output:
#   golangci-lint run -v
# =============================================================================
