# =============================================================================
# Google Cloud Build Configuration for Howlerops Backend
# =============================================================================
# This configuration automates the CI/CD pipeline for deploying to Cloud Run:
# 1. Builds the Docker container image
# 2. Pushes to Google Container Registry (GCR)
# 3. Deploys to Cloud Run with production configuration
#
# Triggered by: Git push to main branch (configured in Cloud Build triggers)
# =============================================================================

steps:
  # ---------------------------------------------------------------------------
  # Step 1: Build the container image
  # ---------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "-f"
      - "backend-go/Dockerfile"
      - "-t"
      - "gcr.io/$PROJECT_ID/howlerops-backend:$SHORT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/howlerops-backend:latest"
      - "--cache-from"
      - "gcr.io/$PROJECT_ID/howlerops-backend:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "."

  # ---------------------------------------------------------------------------
  # Step 2: Push the container image to Container Registry
  # ---------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image-sha"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/howlerops-backend:$SHORT_SHA"
    waitFor: ["build-image"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-image-latest"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/howlerops-backend:latest"
    waitFor: ["build-image"]

  # ---------------------------------------------------------------------------
  # Step 3: Deploy to Cloud Run
  # ---------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloud-run"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        set -euo pipefail

        SERVICE_NAME="howlerops-backend"
        REGION="us-central1"
        IMAGE="gcr.io/$PROJECT_ID/${SERVICE_NAME}:$SHORT_SHA"
        SERVICE_ACCOUNT="howlerops-backend@$PROJECT_ID.iam.gserviceaccount.com"

        echo "Deploying $SERVICE_NAME with image $IMAGE"
        echo "Building secret list..."

        SECRET_ARGS="--set-secrets=TURSO_URL=turso-url:latest,TURSO_AUTH_TOKEN=turso-auth-token:latest,RESEND_API_KEY=resend-api-key:latest,JWT_SECRET=jwt-secret:latest"

        add_optional_secret() {
          local env_name="$1"
          local secret_name="$2"
          if gcloud secrets describe "$secret_name" >/dev/null 2>&1; then
            echo "  ✓ Using $secret_name for $env_name"
            SECRET_ARGS="${SECRET_ARGS},${env_name}=${secret_name}:latest"
          else
            echo "  - Secret $secret_name not found (skipping $env_name)"
          fi
        }

        add_optional_secret "RESEND_FROM_EMAIL" "resend-from-email"
        add_optional_secret "GOOGLE_CLIENT_ID" "google-oauth-client-id"
        add_optional_secret "GOOGLE_CLIENT_SECRET" "google-oauth-client-secret"
        add_optional_secret "GITHUB_CLIENT_ID" "github-oauth-client-id"
        add_optional_secret "GITHUB_CLIENT_SECRET" "github-oauth-client-secret"

        echo "Secret flag: ${SECRET_ARGS}"

        gcloud run deploy "${SERVICE_NAME}" \
          --image="${IMAGE}" \
          --region="${REGION}" \
          --platform=managed \
          --allow-unauthenticated \
          --port=8500 \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=80 \
          --timeout=300 \
          --set-env-vars="ENVIRONMENT=production,LOG_FORMAT=json,LOG_LEVEL=info" \
          "${SECRET_ARGS}" \
          --service-account="${SERVICE_ACCOUNT}" \
          --labels="app=howlerops,component=backend,managed-by=cloud-build"
    waitFor: ["push-image-sha"]

  # ---------------------------------------------------------------------------
  # Step 4: Run smoke tests against deployed service
  # ---------------------------------------------------------------------------
  - name: "gcr.io/cloud-builders/gcloud"
    id: "smoke-test"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Waiting for service to be ready..."
        sleep 10
        SERVICE_URL=$$(gcloud run services describe howlerops-backend --region=us-central1 --format='value(status.url)')
        echo "Testing health endpoint: $$SERVICE_URL/health"
        curl -f -s -o /dev/null -w "%{http_code}" $$SERVICE_URL/health || exit 1
        echo "Health check passed!"
    waitFor: ["deploy-cloud-run"]

# Tag images for artifact registry
images:
  - "gcr.io/$PROJECT_ID/howlerops-backend:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/howlerops-backend:latest"

# Build options
options:
  # Use high-CPU machine for faster builds
  machineType: "N1_HIGHCPU_8"
  # Enable Docker BuildKit for better caching
  env:
    - "DOCKER_BUILDKIT=1"
  # Substitute variables
  substitutionOption: "ALLOW_LOOSE"

# Timeout for entire build
timeout: "1800s"

# Logging configuration
logsBucket: "gs://howlerops-prod_cloudbuild/logs"
