// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CatalogTag represents a reusable tag
 */
export class CatalogTag {
    /**
     * Creates a new CatalogTag instance.
     * @param {Partial<CatalogTag>} [$$source = {}] - The source object to create the CatalogTag.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["organization_id"] = undefined;
        }
        if (!("is_system" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_system"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CatalogTag instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CatalogTag}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CatalogTag(/** @type {Partial<CatalogTag>} */($$parsedSource));
    }
}

/**
 * ColumnCatalogEntry represents catalog metadata for a column
 */
export class ColumnCatalogEntry {
    /**
     * Creates a new ColumnCatalogEntry instance.
     * @param {Partial<ColumnCatalogEntry>} [$$source = {}] - The source object to create the ColumnCatalogEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("table_catalog_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_catalog_id"] = "";
        }
        if (!("column_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["pii_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["pii_confidence"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnCatalogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnCatalogEntry}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new ColumnCatalogEntry(/** @type {Partial<ColumnCatalogEntry>} */($$parsedSource));
    }
}

/**
 * SearchFilters represents search filtering options
 */
export class SearchFilters {
    /**
     * Creates a new SearchFilters instance.
     * @param {Partial<SearchFilters>} [$$source = {}] - The source object to create the SearchFilters.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["connection_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["schema_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["organization_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["limit"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchFilters instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchFilters}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField2_0($$parsedSource["tags"]);
        }
        return new SearchFilters(/** @type {Partial<SearchFilters>} */($$parsedSource));
    }
}

/**
 * SearchResult represents a single search result
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * 'table' or 'column'
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("schema_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema_name"] = "";
        }
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["column_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (!("relevance_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["relevance_score"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField7_0($$parsedSource["tags"]);
        }
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * SearchResults represents a collection of search results
 */
export class SearchResults {
    /**
     * Creates a new SearchResults instance.
     * @param {Partial<SearchResults>} [$$source = {}] - The source object to create the SearchResults.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * @member
             * @type {(SearchResult | null)[]}
             */
            this["results"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResults instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResults}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new SearchResults(/** @type {Partial<SearchResults>} */($$parsedSource));
    }
}

/**
 * TableCatalogEntry represents catalog metadata for a table
 */
export class TableCatalogEntry {
    /**
     * Creates a new TableCatalogEntry instance.
     * @param {Partial<TableCatalogEntry>} [$$source = {}] - The source object to create the TableCatalogEntry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("schema_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema_name"] = "";
        }
        if (!("table_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table_name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["steward_user_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["tags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["organization_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(ColumnCatalogEntry | null)[] | undefined}
             */
            this["columns"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("created_by" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_by"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableCatalogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableCatalogEntry}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField8_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField8_0($$parsedSource["columns"]);
        }
        return new TableCatalogEntry(/** @type {Partial<TableCatalogEntry>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SearchResult.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ColumnCatalogEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType5);
