# Grafana datasource configuration for Prometheus

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: POST
      timeInterval: "5s"
      queryTimeout: "60s"
      manageAlerts: true
      alertmanagerUid: "alertmanager"
    secureJsonData: {}
    version: 1
    editable: true

  - name: HowlerOps Logs
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    withCredentials: false
    jsonData:
      httpMethod: GET
      maxLines: 1000
      derivedFields:
        - datasourceUid: "prometheus"
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
    version: 1
    editable: true