// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKeyboardBinding(arg1, arg2) {
  return window['go']['main']['App']['AddKeyboardBinding'](arg1, arg2);
}

export function CancelQueryStream(arg1) {
  return window['go']['main']['App']['CancelQueryStream'](arg1);
}

export function CheckBiometricAvailability() {
  return window['go']['main']['App']['CheckBiometricAvailability']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckStoredToken(arg1) {
  return window['go']['main']['App']['CheckStoredToken'](arg1);
}

export function ClearAIMemorySessions() {
  return window['go']['main']['App']['ClearAIMemorySessions']();
}

export function ClearRecentFiles() {
  return window['go']['main']['App']['ClearRecentFiles']();
}

export function ConfigureAIProvider(arg1) {
  return window['go']['main']['App']['ConfigureAIProvider'](arg1);
}

export function CopyFile(arg1, arg2) {
  return window['go']['main']['App']['CopyFile'](arg1, arg2);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateDirectory(arg1) {
  return window['go']['main']['App']['CreateDirectory'](arg1);
}

export function CreateTempFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTempFile'](arg1, arg2, arg3);
}

export function DeleteAIMemorySession(arg1) {
  return window['go']['main']['App']['DeleteAIMemorySession'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function DeleteQueryRows(arg1) {
  return window['go']['main']['App']['DeleteQueryRows'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function DeleteSyntheticView(arg1) {
  return window['go']['main']['App']['DeleteSyntheticView'](arg1);
}

export function DeleteWebAuthnCredential(arg1) {
  return window['go']['main']['App']['DeleteWebAuthnCredential'](arg1);
}

export function ExecuteMultiDatabaseQuery(arg1) {
  return window['go']['main']['App']['ExecuteMultiDatabaseQuery'](arg1);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExecuteQueryStream(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQueryStream'](arg1, arg2, arg3);
}

export function ExecuteReadOnlyQuery(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteReadOnlyQuery'](arg1, arg2, arg3, arg4);
}

export function ExecuteReadOnlyQueryWithPagination(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteReadOnlyQueryWithPagination'](arg1, arg2, arg3, arg4, arg5);
}

export function ExecuteSyntheticQuery(arg1) {
  return window['go']['main']['App']['ExecuteSyntheticQuery'](arg1);
}

export function ExplainQuery(arg1, arg2) {
  return window['go']['main']['App']['ExplainQuery'](arg1, arg2);
}

export function ExportKeyboardBindings() {
  return window['go']['main']['App']['ExportKeyboardBindings']();
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function FinishWebAuthnAuthentication(arg1, arg2) {
  return window['go']['main']['App']['FinishWebAuthnAuthentication'](arg1, arg2);
}

export function FinishWebAuthnRegistration(arg1, arg2) {
  return window['go']['main']['App']['FinishWebAuthnRegistration'](arg1, arg2);
}

export function FixSQLError(arg1, arg2, arg3) {
  return window['go']['main']['App']['FixSQLError'](arg1, arg2, arg3);
}

export function FixSQLErrorWithOptions(arg1) {
  return window['go']['main']['App']['FixSQLErrorWithOptions'](arg1);
}

export function GenerateSQLFromNaturalLanguage(arg1) {
  return window['go']['main']['App']['GenerateSQLFromNaturalLanguage'](arg1);
}

export function GenericChat(arg1) {
  return window['go']['main']['App']['GenericChat'](arg1);
}

export function GetAIConfiguration() {
  return window['go']['main']['App']['GetAIConfiguration']();
}

export function GetAIProviderStatus() {
  return window['go']['main']['App']['GetAIProviderStatus']();
}

export function GetAllKeyboardBindings() {
  return window['go']['main']['App']['GetAllKeyboardBindings']();
}

export function GetAppIcon() {
  return window['go']['main']['App']['GetAppIcon']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAvailableEnvironments() {
  return window['go']['main']['App']['GetAvailableEnvironments']();
}

export function GetConnectionCount() {
  return window['go']['main']['App']['GetConnectionCount']();
}

export function GetConnectionHealth(arg1) {
  return window['go']['main']['App']['GetConnectionHealth'](arg1);
}

export function GetConnectionIDs() {
  return window['go']['main']['App']['GetConnectionIDs']();
}

export function GetConnectionStats() {
  return window['go']['main']['App']['GetConnectionStats']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetDarkIcon() {
  return window['go']['main']['App']['GetDarkIcon']();
}

export function GetDatabaseTypeInfo(arg1) {
  return window['go']['main']['App']['GetDatabaseTypeInfo'](arg1);
}

export function GetDatabaseVersion(arg1) {
  return window['go']['main']['App']['GetDatabaseVersion'](arg1);
}

export function GetDownloadsPath() {
  return window['go']['main']['App']['GetDownloadsPath']();
}

export function GetEditableMetadata(arg1) {
  return window['go']['main']['App']['GetEditableMetadata'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetHomePath() {
  return window['go']['main']['App']['GetHomePath']();
}

export function GetKeyboardBindingsByCategory() {
  return window['go']['main']['App']['GetKeyboardBindingsByCategory']();
}

export function GetLightIcon() {
  return window['go']['main']['App']['GetLightIcon']();
}

export function GetMultiConnectionSchema(arg1) {
  return window['go']['main']['App']['GetMultiConnectionSchema'](arg1);
}

export function GetOAuthURL(arg1) {
  return window['go']['main']['App']['GetOAuthURL'](arg1);
}

export function GetPassword(arg1, arg2) {
  return window['go']['main']['App']['GetPassword'](arg1, arg2);
}

export function GetQuerySuggestions(arg1, arg2) {
  return window['go']['main']['App']['GetQuerySuggestions'](arg1, arg2);
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetSchemaCacheStats() {
  return window['go']['main']['App']['GetSchemaCacheStats']();
}

export function GetSchemas(arg1) {
  return window['go']['main']['App']['GetSchemas'](arg1);
}

export function GetStoredUserInfo(arg1) {
  return window['go']['main']['App']['GetStoredUserInfo'](arg1);
}

export function GetSupportedDatabaseTypes() {
  return window['go']['main']['App']['GetSupportedDatabaseTypes']();
}

export function GetSyntheticSchema() {
  return window['go']['main']['App']['GetSyntheticSchema']();
}

export function GetSyntheticView(arg1) {
  return window['go']['main']['App']['GetSyntheticView'](arg1);
}

export function GetTableStructure(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableStructure'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function GetTempDir() {
  return window['go']['main']['App']['GetTempDir']();
}

export function GetWorkspaceFiles(arg1, arg2) {
  return window['go']['main']['App']['GetWorkspaceFiles'](arg1, arg2);
}

export function HandleKeyboardEvent(arg1) {
  return window['go']['main']['App']['HandleKeyboardEvent'](arg1);
}

export function HasPassword(arg1) {
  return window['go']['main']['App']['HasPassword'](arg1);
}

export function HasWebAuthnCredential(arg1) {
  return window['go']['main']['App']['HasWebAuthnCredential'](arg1);
}

export function HealthCheckAll() {
  return window['go']['main']['App']['HealthCheckAll']();
}

export function ImportKeyboardBindings(arg1) {
  return window['go']['main']['App']['ImportKeyboardBindings'](arg1);
}

export function InsertQueryRow(arg1) {
  return window['go']['main']['App']['InsertQueryRow'](arg1);
}

export function InvalidateAllSchemas() {
  return window['go']['main']['App']['InvalidateAllSchemas']();
}

export function InvalidateSchemaCache(arg1) {
  return window['go']['main']['App']['InvalidateSchemaCache'](arg1);
}

export function ListConnectionDatabases(arg1) {
  return window['go']['main']['App']['ListConnectionDatabases'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListReports() {
  return window['go']['main']['App']['ListReports']();
}

export function ListSyntheticViews() {
  return window['go']['main']['App']['ListSyntheticViews']();
}

export function LoadAIMemorySessions() {
  return window['go']['main']['App']['LoadAIMemorySessions']();
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function OnUrlOpen(arg1) {
  return window['go']['main']['App']['OnUrlOpen'](arg1);
}

export function OpenDownloadPage() {
  return window['go']['main']['App']['OpenDownloadPage']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OptimizeQuery(arg1, arg2) {
  return window['go']['main']['App']['OptimizeQuery'](arg1, arg2);
}

export function ParseQueryConnections(arg1) {
  return window['go']['main']['App']['ParseQueryConnections'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RecallAIMemorySessions(arg1, arg2) {
  return window['go']['main']['App']['RecallAIMemorySessions'](arg1, arg2);
}

export function RefreshSchema(arg1) {
  return window['go']['main']['App']['RefreshSchema'](arg1);
}

export function RemoveConnection(arg1) {
  return window['go']['main']['App']['RemoveConnection'](arg1);
}

export function RemoveFromRecentFiles(arg1) {
  return window['go']['main']['App']['RemoveFromRecentFiles'](arg1);
}

export function RemoveKeyboardBinding(arg1) {
  return window['go']['main']['App']['RemoveKeyboardBinding'](arg1);
}

export function ResetKeyboardBindings() {
  return window['go']['main']['App']['ResetKeyboardBindings']();
}

export function RunReport(arg1) {
  return window['go']['main']['App']['RunReport'](arg1);
}

export function SaveAIMemorySessions(arg1) {
  return window['go']['main']['App']['SaveAIMemorySessions'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFileDialog() {
  return window['go']['main']['App']['SaveFileDialog']();
}

export function SaveReport(arg1) {
  return window['go']['main']['App']['SaveReport'](arg1);
}

export function SaveSyntheticView(arg1) {
  return window['go']['main']['App']['SaveSyntheticView'](arg1);
}

export function SaveToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveToDownloads'](arg1, arg2);
}

export function ShowErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowErrorDialog'](arg1, arg2);
}

export function ShowInfoDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowInfoDialog'](arg1, arg2);
}

export function ShowNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2, arg3);
}

export function ShowQuestionDialog(arg1, arg2) {
  return window['go']['main']['App']['ShowQuestionDialog'](arg1, arg2);
}

export function StartClaudeCodeLogin(arg1) {
  return window['go']['main']['App']['StartClaudeCodeLogin'](arg1);
}

export function StartCodexLogin(arg1) {
  return window['go']['main']['App']['StartCodexLogin'](arg1);
}

export function StartWebAuthnAuthentication(arg1) {
  return window['go']['main']['App']['StartWebAuthnAuthentication'](arg1);
}

export function StartWebAuthnRegistration(arg1, arg2) {
  return window['go']['main']['App']['StartWebAuthnRegistration'](arg1, arg2);
}

export function StorePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorePassword'](arg1, arg2, arg3);
}

export function StreamAIQueryAgent(arg1) {
  return window['go']['main']['App']['StreamAIQueryAgent'](arg1);
}

export function SuggestVisualization(arg1) {
  return window['go']['main']['App']['SuggestVisualization'](arg1);
}

export function SwitchConnectionDatabase(arg1) {
  return window['go']['main']['App']['SwitchConnectionDatabase'](arg1);
}

export function TestAIProvider(arg1) {
  return window['go']['main']['App']['TestAIProvider'](arg1);
}

export function TestAnthropicConnection(arg1, arg2) {
  return window['go']['main']['App']['TestAnthropicConnection'](arg1, arg2);
}

export function TestClaudeCodeConnection(arg1, arg2) {
  return window['go']['main']['App']['TestClaudeCodeConnection'](arg1, arg2);
}

export function TestCodexConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestCodexConnection'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function TestHuggingFaceConnection(arg1, arg2) {
  return window['go']['main']['App']['TestHuggingFaceConnection'](arg1, arg2);
}

export function TestOllamaConnection(arg1, arg2) {
  return window['go']['main']['App']['TestOllamaConnection'](arg1, arg2);
}

export function TestOpenAIConnection(arg1, arg2) {
  return window['go']['main']['App']['TestOpenAIConnection'](arg1, arg2);
}

export function UpdateQueryRow(arg1) {
  return window['go']['main']['App']['UpdateQueryRow'](arg1);
}

export function ValidateMultiQuery(arg1) {
  return window['go']['main']['App']['ValidateMultiQuery'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
