name: Go Integration Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *' # daily at 06:00 UTC

jobs:
  go-integration:
    name: Go Integration Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          cache: true

      - name: Run backend integration tests (-tags=integration)
        working-directory: backend-go
        run: go test -tags=integration ./...
